# DISH SKA001 SPECIFIC CI

.ska001-env:
  variables:
    DISH_INDEX: "001"
    SPFRX_TANGO_INSTANCE: rxpu-2
    SPFRX_ADDRESS: 10.165.3.21
    DISH_ID: ska001
    SPFRX_IN_THE_LOOP: "false"
  rules:
    - if: $DISH_IDS !~ /.*SKA001.*/
      when: never

2-deploy-dishlmc-ska001:
  extends:
    - .deploy-additional-lmc
    - .ska001-env
  needs:
    - 1-deploy-dishlmc-ska063
    - deploy-aa05-dishes
  when: on_success
  environment:
    on_stop: 2-uninstall-dishlmc-ska001

2-redeploy-dishlmc-ska001:
  extends:
    - .redeploy-dish-lmc
    - .ska001-env
  when: manual
  # variables:
  #   DISH_LMC_EXTRA_PARAMS: -f charts/dish-lmc/values-cetc.yaml --set ska-dish-lmc.ska-mid-dish-ds-manager.dishstructuremanager.dsSim.fqdn=$DS_SIM_OPCUA_FQDN
  environment:
    on_stop: 2-uninstall-dishlmc-ska001

2-uninstall-dishlmc-ska001:
  extends:
    - .destroy-dish-lmc
    - .ska001-env
