  # name: hum-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hum-{{ .Values.device_name }}
  labels:
    app.kubernetes.io/name: hardware-under-maintenance
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hardware-under-maintenance
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hardware-under-maintenance
    spec:
      # serviceAccountName: test-hardware-under-maintenance
      containers:
        - name: hardware-under-maintenance
          securityContext:
            {}
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
              {{- toYaml .Values.resources | nindent 12 }}
