apiVersion: v2
name: ska-mid-itf
description: An umbrella Helm chart so that Helm Charts of Test Equipment (SigGen and SpectrAna), SkySimCtl can be deployed to a kubernetes cluster
type: application
version: 0.1.0-dev.c
appVersion: 0.1.0-dev.c
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  # Tango
  - name: ska-tango-base
    version: 0.4.4 # Check latest version
    repository: https://artefact.skao.int/repository/helm-internal

  - name: ska-tango-util
    version: 0.4.5 # Check latest version
    repository: https://artefact.skao.int/repository/helm-internal

  # SKA Test Equipment
  - name: ska-ser-test-equipment
    version: 0.7.1-at757-dev.c0323d010 # check latest version
    repository: https://gitlab.com/api/v4/projects/31506252/packages/helm/dev
    alias: test-equipment
    condition: test-equipment.enabled

  # TARANTA SUITE
  - name: ska-tango-taranta
    version: 2.2.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
  - name: ska-tango-tangogql
    version: 1.3.6
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled

  - name: ds-sim
    version: 0.1.6
    repository: https://artefact.skao.int/repository/helm-internal
