global:
  facility: test-itf
  sub-system:
    ska-tango-base:
      enabled: false

ska-tango-base:
  itango:
    enabled: true

test-equipment:
  legacy_compatibility: true
  enabled: true
  simulators:
    enabled: false
  deviceServers:
    spectrumanalyser:
      devices: [] # Now we need to put back the Tektronix
    signalgenerator:
      devices:
        - name: smb100a
          model: SMB100A
          host: 10.165.3.1
          port: 5025
          resources:
            limits:
              skao.int/signal-generator-01: "1"
