[tool.poetry]
name = "ska-mid-itf"
version = "0.1.0"
description = "SCPI and Tango enabled Sky Simulator Controller for a RaspberryPi and container runtime testing."
authors = ["ATLAS"]
license = "BSD 3-Clause"
readme = "README.md"
packages = [{include = "ska_sky_simulator_controller", from = "src"}]

[[tool.poetry.source]]
name = 'skao'
url = 'https://artefact.skao.int/repository/pypi-internal/simple'

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
ska-tango-testing = "^0.5.3"
pytest-bdd = ">=5.0.0,<6.0.0"
ska-ser-test-equipment = "^0.6.2"
pytest = ">=6.2.5,<7.0.0"
ska-ser-skallop = "2.29.1"
ska-tmc-cdm = "7.3.1"

[tool.poetry.group.docs.dependencies]
Sphinx = "^5.1.1"
sphinx-rtd-theme = "^1.0.0"
recommonmark = "^0.7.1"
markupsafe = "^2.1.0"

[tool.poetry.dev-dependencies]
black = {version = "^22.6.0", allow-prereleases = true}

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
pylint = "^2.15.10"
pylint-junit = "^0.3.2"
pytest-cov = "^4.0.0"
flake8-docstrings = "^1.7.0"
flake8-rst-docstrings = "^0.3.0"
darglint = "^1.8.1"
mypy = "^0.991"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "-p no:warnings"
testpaths = ["tests/integration"]
log_cli_level = "INFO"
log_cli = "False"
junit_family = "xunit2"
python_classes = "!Test"
#bdd_features_base_dir = "tests"

[tool.build_sphinx]
source-dir = "docs/src"
build-dir = "docs/_build"
all_files = 1
builder = "html"

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 99

[tool.flake8]
max-line-length = 99

[tool.black]
line_length = 99

