[tool.poetry]
name = "ska-mid-itf"
version = "0.0.0"
description = "User facing layer for SKA Mid ITF"
authors = ["ATLAS"]
license = "BSD 3-Clause"
readme = "README.md"
packages = [{include = "sky_simulator_controller", from = "src"}]

[[tool.poetry.source]]
name = 'ska-nexus'
url = 'https://artefact.skao.int/repository/pypi-internal/simple'

[tool.poetry.dependencies]
python = "^3.9"
Sphinx = "^5.1.0"
sphinx-rtd-theme = "^1.0.0"
recommonmark = "^0.7.1"

[tool.poetry.dev-dependencies]
black = {version = "^22.6.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
