apiVersion: v2
name: status-page
description: A helm chart to deploy a status page to a kubernetes cluster.
type: application
version: 0.1.0
appVersion: 0.1.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  # Tango
  - name: ska-tango-util
    version: 0.3.17 # Check latest version
    repository: https://artefact.skao.int/repository/helm-internal

  - name: ska-tango-base
    version: 0.3.17 # Check latest version
    repository: https://artefact.skao.int/repository/helm-internal

  # Taranta Dashboards
  - name: ska-tango-taranta-dashboard-pvc
    version: 1.3.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
