.oda:
  tags:
    - ska-k8srunner-za-itf
  variables:
    CONFIG: mid
    K8S_CHART: ska-mid
    KUBE_APP: ska-db-oda
    INGRESS_HOST: "k8s.miditf.internal.skao.int"
    CLUSTER_DOMAIN: "miditf.internal.skao.int"
    ODA_ENABLERS: "-f .gitlab/ci/za-itf/ci-ska-db-oda-commit-ref/oda-enablers.yaml"
    TANGO_DATABASE_DS: tango-databaseds
    MINIKUBE: "false"
    CLUSTER_DOMAIN_POSTFIX: miditf.internal.skao.int
  environment:
    name: sut/oda/$KUBE_NAMESPACE
    kubernetes:
      namespace: $KUBE_NAMESPACE
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
  when: manual
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_PIPELINE_ID"
    paths:
      - "build/"

.oda-persistent:
  extends:
    - .oda
  stage: deploy-oda
  variables:
    KUBE_NAMESPACE: ska-db-oda

deploy-oda:
  extends:
    - .oda-persistent
  script:
    - make k8s-install-chart
  after_script:
    - bash .make/resources/gitlab_section.sh deployment-config "Output deployment config information" make get-deployment-config-info
  environment:
    on_stop: destroy-oda

destroy-oda:
  extends:
    - .oda-persistent
  script:
    - !reference [.uninstall-chart, script]
  environment:
    action: stop
