- name: Create user accounts
  ansible.builtin.user:
    name: "{{ current_user }}"
    shell: /bin/bash
    group: "{{ team_primary_group }}"
    groups: "{{ filtered_user_groups[current_user] }}"
    append: true

- name: Add to sudoers
  when: "'sudo' in filtered_user_groups[current_user]"
  ansible.builtin.lineinfile:
    line: "{{ current_user }} ALL=(ALL) NOPASSWD:ALL"
    path: "/etc/sudoers.d/99-atlas-team"
    regex: "{{ current_user }}"
    create: true
    owner: "root"
    group: "root"
    mode: "440"
