---

- name: Setup variables
  block:
    - name: Set user groups
      ansible.builtin.set_fact:
        user_setup_user_groups: "{{ user_config['groups'] }}"
    - name: Set users
      ansible.builtin.set_fact:
        user_setup_users: "{{ user_config['users'] }}"
    - name: Set add_to_sudoers
      ansible.builtin.set_fact:
        user_setup_add_to_sudoers: "yes"
      when: "'sudo' in user_setup_user_groups"

  # Creates new users and adds them to sudoers if so configured.
- name: Create users
  ansible.builtin.include_tasks: "create_user.yml"
  args:
    apply:
      become: true
  loop: "{{ user_setup_users }}"
  loop_control:
    loop_var: current_user
  when: createusers and current_user in users

- name: Remove users
  ansible.builtin.include_tasks: "remove_user.yml"
  args:
    apply:
      become: true
  loop: "{{ user_setup_users }}"
  loop_control:
    loop_var: current_user
  when: removeusers and current_user in users

- name: Add to groups
  become: true
  ansible.builtin.user:
    name: "{{ current_user }}"
    groups: "{{ user_setup_user_groups }}"
    append: true
  loop: "{{ user_setup_users }}"
  loop_control:
    loop_var: current_user
  when: add_to_groups and current_user in users
