# DISH SKA100 SPECIFIC CI

.ska100-env:
  variables:
    DISH_ID: ska100
    DISH_INDEX: "100"
    SPFRX_TANGO_INSTANCE: rxpu-4
    SPFRX_ADDRESS: 10.165.3.23
    SPFRX_IN_THE_LOOP: "false"
    SPFC_IN_THE_LOOP: "false"
    # Remember to explicitly quote the URL to prevent parsing errors
    DISH_LMC_EDA_PARAMS: '--set ska-tango-archiver.configuration_file_url="https://gitlab.com/ska-telescope/ska-mid/-/raw/27.3.0/tmdata/mid-itf-staging-archiver-configs/dish-lmc-ska100.yaml?ref_type=tags&inline=false"'

4-deploy-dishlmc-ska100:
  extends:
    - .deploy-additional-lmc
    - .ska100-env
  needs:
    - 1-deploy-dishlmc-ska001
    - deploy-aa05-dishes
  when: on_success
  environment:
    on_stop: 4-uninstall-dishlmc-ska100

4-redeploy-dishlmc-ska100:
  extends:
    - .redeploy-dish-lmc
    - .ska100-env
  when: manual
  environment:
    on_stop: 4-uninstall-dishlmc-ska100

4-uninstall-dishlmc-ska100:
  extends:
    - .destroy-aa05-dishes
    - .ska100-env
