# DISH SKA100 SPECIFIC CI

.ska100-env:
  variables:
    DISH_INDEX: "100"
    SPFRX_TANGO_INSTANCE: rxpu-4
    SPFRX_ADDRESS: 10.165.3.23
    DISH_ID: ska100
    SPFRX_IN_THE_LOOP: "false"
    SPFC_IN_THE_LOOP: "true"

4-deploy-dishlmc-ska100:
  extends:
    - .deploy-additional-lmc
    - .ska100-env
  needs:
    - 1-deploy-dishlmc-ska063
    - deploy-aa05-dishes
  when: on_success
  environment:
    on_stop: 4-uninstall-dishlmc-ska100

4-redeploy-dishlmc-ska100:
  extends:
    - .redeploy-dish-lmc
    - .ska100-env
  when: manual
  environment:
    on_stop: 4-uninstall-dishlmc-ska100

4-uninstall-dishlmc-ska100:
  extends:
    - .destroy-aa05-dishes
    - .ska100-env
