# DISH SKA063 SPECIFIC CI

.ska063-env:
  variables:
    DISH_INDEX: "063"
    # SPFRX_TANGO_INSTANCE: spfrx-???
    # SPFRX_ADDRESS:
    DISH_ID: ska063
    SPFRX_IN_THE_LOOP: "false"
    SPFC_IN_THE_LOOP: "true"

deploy-dishlmc-ska063:
  extends:
    - .deploy-dish-lmc
    - .ska063-env
  ### TEMPORARILY DISABLED DEPLOYMENT OF DS-SIM - SEE .gitlab/ci/za-itf/ds-sim-skaXXX/.pipeline.yaml
  # needs:
  #   - deploy-ds-sim-ska063
  # when: on_success
  # variables:
  #   DISH_LMC_EXTRA_PARAMS: -f charts/dish-lmc/values-cetc.yaml --set ska-dish-lmc.ska-mid-dish-ds-manager.dishstructuremanager.dsSim.fqdn=$DS_SIM_OPCUA_FQDN
  when: manual
  environment:
    on_stop: uninstall-dishlmc-ska063

redeploy-dishlmc-ska063:
  extends:
    - .redeploy-dish-lmc
    - .ska063-env
  when: manual
  # variables:
  #   DISH_LMC_EXTRA_PARAMS: -f charts/dish-lmc/values-cetc.yaml --set ska-dish-lmc.ska-mid-dish-ds-manager.dishstructuremanager.dsSim.fqdn=$DS_SIM_OPCUA_FQDN
  environment:
    on_stop: uninstall-dishlmc-ska063

uninstall-dishlmc-ska063:
  extends:
    - .destroy-dish-lmc
    - .ska063-env
