.integration-env:
  stage: integration
  tags:
    - ska-k8srunner-za-itf
  extends:
    - .integration_rules
  variables:
    CONFIG: mid
    # HELM_RELEASE: "integration-$CI_COMMIT_REF_SLUG"
    HELM_RELEASE: "integration-main"
    KUBE_NAMESPACE: "integration"
    KUBE_NAMESPACE_SDP: "$KUBE_NAMESPACE-sdp"
    SERVICE_ACCOUNT: "ci-svc-integration"
    ARCHIVER_DBNAME: "integration_archiver_db"
    KEEP_NAMESPACE: "true"
    K8S_CHART: "ska-mid-itf-sut"
    CLUSTER_DOMAIN_POSTFIX: miditf.internal.skao.int
    KUBE_APP: ska-mid-sut
    INGRESS_HOST: "k8s.miditf.internal.skao.int"
    CLUSTER_DOMAIN: "miditf.internal.skao.int"
    K8S_EXTRA_PARAMS: "--set global.ska-tango-archiver.enabled=true --set ska-tango-archiver.enabled=true --set ska-tango-archiver.dbuser=admin --set ska-tango-archiver.dbpassword=${EDA_DB_PASSWORD} --set ska-tango-archiver.archviewer.instances[0].timescale_login=admin:${EDA_DB_PASSWORD} --set ska-tango-archiver.archviewer.instances[0].timescale_databases=itf_eda --set ska-tango-archiver.archviewer.instances[0].timescale_host=10.164.11.33 --set ska-tango-archiver.archviewer.instances[0].name=mid"
    TANGO_DATABASE_DS: tango-databaseds
    K8S_AUTH_NAMESPACES: "$KUBE_NAMESPACE $KUBE_NAMESPACE_SDP"
    K8S_AUTH_SERVICE_ACCOUNT: "ci-svc-ska-miditf-$CI_PIPELINE_ID"
    PDU_IP: "10.20.2.14"
    # HARDWARE AND DISH IN THE LOOP SETTINGS
    CBF_HW_IN_THE_LOOP: "false"
    DISH_LMC_IN_THE_LOOP: "true"

deploy-sut-integration:
  extends:
    - .deploy
    - .integration-env
  image: $DEPLOY_IMAGE
  environment:
    name: mid-itf/ska-$CONFIG-integration
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: $KUBE_NAMESPACE
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
    on_stop: destroy-sut-integration

redeploy-sut-integration:
  extends:
    - .redeploy
    - .integration-env
  environment:
    name: mid-itf/ska-$CONFIG-integration
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: $KUBE_NAMESPACE
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
    on_stop: destroy-sut-integration

info-sut-integration:
  extends:
    - .info
    - .integration-env

destroy-sut-integration:
  extends:
    - .cleanup
    - .integration-env
  environment:
    name: mid-itf/ska-$CONFIG-integration
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: $KUBE_NAMESPACE
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
    action: stop

.test-integration-rules:
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: never
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - when: never

test-end-to-end-integration:
  stage: test
  extends:
    - .integration-env
    - .test-end-to-end-with-hw
    - .test-integration-rules

test-telescope-on-integration:
  stage: test
  extends:
    - .integration-env
    - .test-telescope-on-with-hw
    - .test-integration-rules

test-scan-integration:
  stage: test
  extends:
    - .integration-env
    - .test-scan-with-hw
    - .test-integration-rules

test-telescope-off-integration:
  stage: test
  extends:
    - .integration-env
    - .test-telescope-off-with-hw
    - .test-integration-rules