
.integration-env:
  stage: integration
  extends:
    - .integration_rules
  variables:
    CONFIG: mid
    HELM_RELEASE: "integration-$CI_COMMIT_REF_SLUG"
    KUBE_NAMESPACE: "integration"
    KUBE_NAMESPACE_SDP: "$KUBE_NAMESPACE-sdp"
    SERVICE_ACCOUNT: "ci-svc-integration"
    ARCHIVER_DBNAME: "integration_archiver_db"
    KEEP_NAMESPACE: "true"
    K8S_CHART: "ska-$CONFIG"
    K8S_AUTH_NAMESPACES: "$KUBE_NAMESPACE $KUBE_NAMESPACE_SDP"
    K8S_AUTH_SERVICE_ACCOUNT: "ci-svc-ska-miditf-$CI_PIPELINE_ID"
    CLUSTER_DOMAIN_POSTFIX: miditf.internal.skao.int
    DISH_IDS: "SKA001 SKA036 SKA063 SKA100"
    KUBE_APP: ska-mid-sut
    INGRESS_HOST: "k8s.miditf.internal.skao.int"
    CLUSTER_DOMAIN: "miditf.internal.skao.int"
    K8S_EXTRA_PARAMS: "--set global.ska-tango-archiver.enabled=false  --set ska-tango-archiver.enabled=false"
    TANGO_DATABASE_DS: tango-databaseds
    HW_IN_THE_LOOP: "false"
    PDU_IP: "10.20.2.14"

deploy-sut-integration:
  extends:
    - .deploy
    - .integration-env
  environment:
    name: mid-itf/ska-$CONFIG-integration
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: $KUBE_NAMESPACE
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
    on_stop: destroy-sut-integration

redeploy-sut-integration:
  extends:
    - .redeploy
    - .integration-env
  environment:
    name: mid-itf/ska-$CONFIG-integration
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: $KUBE_NAMESPACE
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
    on_stop: destroy-sut-integration

info-sut-integration:
  extends:
    - .info
    - .integration-env

destroy-sut-integration:
  extends:
    - .cleanup
    - .integration-env
  environment:
    name: mid-itf/ska-$CONFIG-integration
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: $KUBE_NAMESPACE
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
    action: stop