- name: Ensure docker is running
  become: true
  ansible.builtin.service:
    name: docker
    state: started

- name: Pull vigil image
  become: true
  community.docker.docker_image:
    name: "{{ vigil_image }}"
    source: pull
    pull:
      platform: amd64

- name: Start vigil
  become: true
  community.docker.docker_container:
    recreate: true
    debug: true
    name: vigil
    image: "{{ vigil_image }}"
    ports:
      - "{{ vigil_port }}:{{ vigil_port }}"
    volumes:
      - /opt/vigil/vigil.cfg:/etc/vigil.cfg
