- name: Find network files
  ansible.builtin.find:
    paths: "{{ network_dir }}"
    patterns:
      - '*.network'
  register: find_result
  tags:
    - spfrx

- name: Map network paths
  ansible.builtin.set_fact:
    network_paths: "{{ find_result.files | map(attribute='path') | list }}"
  tags:
    - spfrx

- name: Create backup dir
  ansible.builtin.file:
    path: "{{ backup_dir }}"
    state: directory
    mode: '0755'
  tags:
    - spfrx

- name: Update DNS in 00-eth.network
  ansible.builtin.import_tasks: network.yml
  vars:
    network_path: "{{ network_dir }}/00-eth.network"
  tags:
    - spfrx

- name: Update DNS in 10-eth.network
  ansible.builtin.import_tasks: network.yml
  vars:
    network_path: "{{ network_dir }}/10-eth.network"
  tags:
    - spfrx

- name: Restart networking
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: systemd-networkd.service
  become: true
  tags:
    - spfrx