- name: Check if ntp file exists before backup
  ansible.builtin.stat:
    path: "{{ ntp_path }}"
  register: ntp_file_stat

- name: Create empty ntp file if it does not exist
  ansible.builtin.file:
    path: "{{ ntp_path }}"
    state: touch
    owner: root
    group: root
    mode: "0644"
  when: not ntp_file_stat.stat.exists

- name: Check if backup folder exists
  ansible.builtin.stat:
    path: "{{ ntp_backup_dir }}"
  register: backup_dir_stat
  when: ntp_file_stat.stat.exists

- name: Create backup folder if missing
  ansible.builtin.file:
    path: "{{ ntp_backup_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when:
    - ntp_file_stat.stat.exists
    - not (backup_dir_stat.stat.exists | default(false))

- name: Find existing numbered backup files
  ansible.builtin.find:
    paths: "{{ ntp_backup_dir }}"
    file_type: file
    patterns:
      - "{{ ntp_path | basename }}*.backup"
      - "{{ ntp_path | basename | regex_replace('\\.conf$', '') }}-*.conf.backup"
  register: existing_backups
  when: ntp_file_stat.stat.exists

- name: Calculate next backup number
  ansible.builtin.set_fact:
    backup_next_index: "{{ (existing_backups.files | length) + 1 }}"
  when: ntp_file_stat.stat.exists

- name: Backup existing file
  ansible.builtin.copy:
    remote_src: true
    src: "{{ ntp_path }}"
    dest: "{{ ntp_backup_dir }}/{{ ntp_path | basename | regex_replace('\\.conf$', '') }}-{{ '%03d' | format(backup_next_index | int) }}.conf.backup"
    owner: root
    group: root
    force: false
    mode: preserve
  when: ntp_file_stat.stat.exists

- name: Configuration for {{ ntp_path | basename }}
  become: true
  ansible.builtin.template:
    src: "{{ ntp_path | basename }}.j2"
    dest: "{{ ntp_path }}"
    mode: "644"
    owner: "root"
    group: "root"


