- name: Configure the TANGO_HOST in the config file
  ansible.builtin.template:
    src: tango_host_conf.ini.j2
    dest: "{{ config_dir }}/tango_host_conf.ini"
    owner: "{{ spfc_usr }}"
    mode: "u=rw,g=r,o=r"
  become: true

- name: Restart systemd service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: spfc.service
  become: true
