# Installation
- name: Install kubectl
  when: install_kubectl
  become: true
  block:
    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl

    - name: Install signing key
      block:
        - name: Add kubectl apt key
          ansible.builtin.get_url:
            url: https://dl.k8s.io/apt/doc/apt-key.gpg
            dest: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
            mode: "u=rw,g=r,o=r"


        - name: Add kubectl apt source
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
            state: present

    - name: Install kubectl
      ansible.builtin.apt:
        pkg:
          - kubectl

# Directories
- name: Ensure shared directory exists
  ansible.builtin.file:
    path: "{{ shared_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"
  become: true

- name: Ensure shared common directory exists
  become: true
  ansible.builtin.file:
    path: "{{ shared_common_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rwx,o=rwx"
