kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifacts-pvc-{{ .Release.Name }}
  labels:
    skao.int/clone-pvc: cbf-ec-pvc
    skao.int/clone-pvc-namespace:  cbf-engineering-console
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: ceph-cephfs
#   volumeMode: Filesystem
