image: python:3.11

stages:
  - lint


# disabled:
# 1. Running ansible-lint fails on Gitlab with: ERROR: Ansible requires the locale encoding to be UTF-8; Detected None.
# 2. Linting fails locally with 36 errors.
.ansible-lint:
  stage: lint
  tags:
  - docker-executor
  allow_failure: true
  script:
  - pip3 install ansible ansible-lint
  - cd ska-cicd-distribute-ssh-keys && make lint