# DISH SKA036 SPECIFIC CI

.ska036-env:
  variables:
    DISH_INDEX: "036"
    SPFRX_TANGO_INSTANCE: spfrx-21
    SPFRX_ADDRESS: 10.165.3.21
    DISH_ID: ska036
    SPFRX_IN_THE_LOOP: "true"

deploy-dishlmc-ska036:
  extends:
    - .deploy-additional-lmc
    - .ska036-env
  needs:
    - deploy-dishlmc-ska001
    # - deploy-aa05-dishes # TEMPORARILY COMMENTED OUT
  when: always # TEMPORARY COMMIT - DELETE WHEN DONE
  # when: on_success # TEMPORARY COMMIT - UNCOMMENT WHEN DONE
  environment:
    on_stop: uninstall-dishlmc-ska036

redeploy-dishlmc-ska036:
  extends:
    - .redeploy-dish-lmc
    - .ska036-env
  needs:
    - redeploy-ds-sim-ska036
  when: on_success
  environment:
    on_stop: uninstall-dishlmc-ska036

uninstall-dishlmc-ska036:
  extends:
    - .destroy-dish-lmc
    - .ska036-env
  needs:
    - remove-ds-sim-ska036
