---
# Make all the realms visible to Gaia

- name: Setup user configuration
  include_tasks: "user_config.yml"
  loop: "{{ users }}"
  loop_control:
    loop_var: current_user

- name: Personalise Login
  become: true
  block:
    - name: Install ASCII art generators
      apt:
        pkg: [figlet, toilet]

    - name: Upload welcome message script
      ansible.builtin.template:
        src: welcome.sh.j2
        dest: "{{ shared_common_dir }}/welcome.sh"
        owner: "root"
        group: "root"
        mode: "u=rwx,g=rx,o=rx" # 0755

    - name: Install generic welcome message
      ansible.builtin.blockinfile:
        path: /etc/profile
        block: |
          # Personalised welcome messages. Change at will :)
          . {{ shared_common_dir }}/welcome.sh
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

# Kubeconfig
- name: Setup Kubeconfig
  when: setup_kubeconfig
  become: true
  block:
    - name: Upload kubeconfig script
      ansible.builtin.template:
        src: kubeconfig_setup.sh.j2
        dest: "{{ shared_common_dir }}/kubeconfig_setup.sh"
        owner: "root"
        group: "root"
        mode: "u=rwx,g=rx,o=rx"

    - name: Install kubeconfig script
      ansible.builtin.blockinfile:
        path: /etc/profile
        block: |
          # Set kubeconfig to default shared config.
          . {{ shared_common_dir }}/kubeconfig_setup.sh
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

