---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: skaxxx-archiver
  namespace: flux-services
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ska-tango-archiver
      version: '2.8.0-dev.cc5da4e46'
      sourceRef:
        kind: HelmRepository
        name: ska-tango-archiver-git
  releaseName: skaxxx-archiver
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  storageNamespace: ska-mid-itf-dish-lmc-skaxxx
  targetNamespace: ska-mid-itf-dish-lmc-skaxxx
  valuesFrom:
  - kind: Secret
    name: vault-shared-ska-tango-archiver
    valuesKey: values.yml
      