apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staging-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: ceph-cephfs
  volumeMode: Filesystem
