[tool.poetry]
name = "dgammon"
version = "0.1.1"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
notebook = "^6.4.12"

[tool.poetry.dev-dependencies]
