---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oso-credentials
spec:
  destination:
    create: true
    name:  oso-credentials 
    type: Opaque
    transformation:
      excludeRaw: true
  mount: mid-itf
  path: ost-credentials
  refreshAfter: 300s
  type: kv-v2
  version: 3
---