---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oso-credentials
spec:
  destination:
    create: true
    name:  oso-credentials 
    type: Opaque
    transformation:
      excludeRaw: true
  mount: kv
  path: users/dayanand_arade/auth_secret
  refreshAfter: 300s
  type: kv-v2
  version: 3
---