{{- if index .Values "ska-oso-integration" "enabled" }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ index .Values "ska-oso-integration" "credentials" "secretName" }}
spec:
  destination:
    create: true
    name: {{ index .Values "ska-oso-integration" "credentials" "secretName" }}
    type: Opaque
    transformation:
      excludeRaw: true
  mount: kv
  path: users/dayanand_arade/auth_secret
  refreshAfter: 300s
  type: kv-v2
---
{{- end }}