{{- if index .Values "ska-octopus-backend" "enabled" }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ index .Values "ska-octopus-backend" "configUi" "password" "secretName" }}
  namespace: octopus
spec:
  destination:
    create: true
    name: {{ index .Values "ska-octopus-backend" "configUi" "password" "secretName" }}
    type: Opaque
    transformation:
      excludeRaw: true
  mount: mid-itf
  path: octopus-credentials
  refreshAfter: 300s
  type: kv-v2
---
{{- end }}
