.aa05-env:
  stage: on_demand_itf_sut
  image: $DEPLOY_IMAGE
  tags:
    - ska-k8srunner-za-itf
  variables:
    CONFIG: mid
    K8S_CHART: ska-mid
    KUBE_NAMESPACE: ci-ska-mid-itf-$CI_COMMIT_REF_NAME
    CLUSTER_DOMAIN: "miditf.internal.skao.int"
    CLUSTER_DOMAIN_POSTFIX: miditf.internal.skao.int
    KUBE_APP: ska-mid-sut
    INGRESS_HOST: "k8s.miditf.internal.skao.int"
    K8S_EXTRA_PARAMS: "--set global.ska-tango-archiver.enabled=false  --set ska-tango-archiver.enabled=false"
    TANGO_DATABASE_DS: tango-databaseds
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: "$CI_COMMIT_TAG"
      variables:
        SPFRX_IN_THE_LOOP: "true"
        KUBE_NAMESPACE: staging-$KUBE_APP-$DISH_ID
        KUBE_NAMESPACE_PREFIX: staging-dish-lmc-
        ENV_NAME: dish.itf/dish-lmc-aa05/staging
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      variables:
        KUBE_NAMESPACE: integration-$KUBE_APP-$DISH_ID
        KUBE_NAMESPACE_PREFIX: integration-dish-lmc-
        ENV_NAME: dish.itf/dish-lmc-aa05/integration
      allow_failure: true
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
      variables:
        KUBE_NAMESPACE: "ci-$KUBE_APP-$DISH_ID-$CI_COMMIT_REF_NAME"
        KUBE_NAMESPACE_PREFIX: ci-dish-lmc-
        KUBE_NAMESPACE_POSTFIX: -$CI_COMMIT_REF_NAME
        ENV_NAME: dish.itf/ci-dish-lmc-aa05-$CI_COMMIT_REF_NAME
      allow_failure: true
  environment:
    name: $ENV_NAME

deploy-aa05-dishes:
  extends:
    - .aa05-env
  script:
    - export PATH=.venv/bin:${PATH} # TEMPORARY COMMIT: fix in one place
    - poetry install
    - echo "Deploying multiple dishes in downstream dish-aiv stage - first deploy ska001 manually"
    - echo "Deploying dishes $DISH_IDS:"
    - make itf-dish-ids
  environment:
    on_stop: uninstall-aa05-dishes
  variables:
    SUT_CHART_DIR: ${CI_PROJECT_DIR}/charts/ska-mid

redeploy-aa05-dishes:
  extends:
    - .aa05-env
  script:
    - echo "Redeploying multiple dishes in downstream dish-aiv stage - first deploy ska001 manually"
    - echo "Redeploying 'SKA001', 'SKA036', 'SKA063', 'SKA100'"
  environment:
    on_stop: uninstall-aa05-dishes

uninstall-aa05-dishes:
  extends:
    - .aa05-env
  script:
    - echo "Uninstalling all dishes in downstream dish-aiv stage"
    - echo "Uninstalling 'SKA001', 'SKA036', 'SKA063', 'SKA100'"
  environment:
    action: stop
