---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "filestash.fullname" .}}
  labels:
    {{- include "filestash.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "filestash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "filestash.selectorLabels" . | nindent 8 }}
    spec:
      hostname: {{ .Values.hostName }}
      containers:
        - name: file-browser
          image: machines/filestash:latest
          env:
            - name: FB_BASEURL
              value: /{{ .Release.Namespace }}/fileserver/
          volumeMounts:
            - name: json-configmap-volume
              mountPath: /app/data/state/config
          ports:
            - containerPort: 8334
              name: http
      volumes:
        - name: json-configmap-volume
          configMap:
            name: json-configmap
            defaultMode: 0777
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "filestash.labels" . | nindent 4 }}
  name: {{ .Values.serviceSettings.name }}
spec:
  externalName: {{ .Values.serviceSettings.name }}
  ports:
  - name: filestash
    protocol: TCP
    port: 8334
    targetPort: 8334
    {{- if eq .Values.env.type "dev"  }}
    nodePort: 32003
    {{- end }}
  selector:
    {{- include "filestash.selectorLabels" . | nindent 4 }}
  type: {{ include "filestash.serviceType" . }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{include "filestash.fullname" .}}
  labels:
    {{- include "filestash.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /{{ .Release.Namespace }}/filestash/(.*)
        backend:
          service:
            name: {{ .Values.serviceSettings.name }}
            port:
              name: filestash
        pathType: ImplementationSpecific
