# DISH SKA063 SPECIFIC CI

.ska063-env:
  variables:
    DISH_ID: ska063
    DISH_INDEX: "063"
    SPFRX_TANGO_INSTANCE: rxpu-3
    SPFRX_ADDRESS: 10.165.3.22
    SPFRX_IN_THE_LOOP: "false"
    SPFC_IN_THE_LOOP: "false"
    # Remember to explicitly quote the URL to prevent parsing errors
    DISH_LMC_EDA_PARAMS: '--set ska-tango-archiver.configuration_file_url="https://gitlab.com/ska-telescope/ska-mid/-/raw/at-3311-eda-config-all-dishes/tmdata/mid-itf-staging-archiver-configs/dish-lmc-ska063.yaml?inline=false"'

3-deploy-dishlmc-ska063:
  extends:
    - .deploy-additional-lmc
    - .ska063-env
  needs:
    - 1-deploy-dishlmc-ska001
    - deploy-aa05-dishes
  when: on_success
  environment:
    on_stop: 3-uninstall-dishlmc-ska063

3-redeploy-dishlmc-ska063:
  extends:
    - .redeploy-dish-lmc
    - .ska063-env
  when: manual
  # variables:
  #   DISH_LMC_EXTRA_PARAMS: -f charts/ska-mid/values-cetc.yaml --set ska-dish-lmc.ska-mid-dish-ds-manager.dishstructuremanager.dsSim.fqdn=$DS_SIM_OPCUA_FQDN
  environment:
    on_stop: 3-uninstall-dishlmc-ska063

3-uninstall-dishlmc-ska063:
  extends:
    - .destroy-dish-lmc
    - .ska063-env
