global:
  facility: mid-itf
  sub-system:
    ska-tango-base:
      enabled: false

ska-tango-base:
  itango:
    enabled: true

test-equipment:
  legacy_compatibility: true
  enabled: true
  simulators:
    enabled: false
  deviceServers:
    progattenuator:
      devices:
        - name: rc1dat800030
          model: RC1DAT800030
          host: 10.165.3.6
          port: 23
          protocol: telnet
    awg:
      devices: []
    signalgenerator:
      devices: []
    sp6t:
      devices: []
    spdt:
      devices: []
    spectrumanalyser:
      devices: []

# TARANTA SUITE
ska-taranta:
  enabled: true
  ingress:
    enabled: true
    nginx: true
    # hostname: k8s.stfc.skao.int
  tangogql:
    replicas: 1
    resources:
      requests:
        cpu: 600m # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem
