apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "ska-ser-k8s-spookd.name" . }}:watch-configmaps"
  labels:
    {{- include "ska-ser-k8s-spookd.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - watch
