# ############################
# # Dish AIV related CICD jobs
# ############################
.dish-env:
  image: $DEPLOY_IMAGE
  variables:
    DISH_LMC_INITIAL_PARAMS: -f charts/dish-lmc/values.yaml --set global.dishes={$DISH_INDEX} --set global.raw_user_account=$CAR_RAW_USERNAME --set global.raw_user_pass=$CAR_RAW_PASSWORD
    CLUSTER_DOMAIN: miditf.internal.skao.int
    INGRESS_HOST: k8s.miditf.internal.skao.int
    K8S_CHART: dish-lmc
    KUBE_APP: dish-lmc
    DISH_ID: ska$DISH_INDEX
    SPFRX_CONSOLE_VER: 0.1.1
    SPFRX_BIN: /usr/local/bin
    SPFRX_LOCAL_DIR: artifacts
    SPFRX_SCRIPTS_DIR: scripts
    SPFRX_TANGO_LOGGING_LEVEL: 4

.deploy_dish_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        KUBE_NAMESPACE: $KUBE_APP-$DISH_ID
        KUBE_NAMESPACE_PREFIX: dish-lmc-
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      variables:
        KUBE_NAMESPACE: "ci-$KUBE_APP-$DISH_ID-$CI_COMMIT_REF_NAME"
        KUBE_NAMESPACE_PREFIX: ci-dish-lmc-
        KUBE_NAMESPACE_POSTFIX: -$CI_COMMIT_REF_NAME

.uninstall_dish_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        KUBE_NAMESPACE: $KUBE_APP-$DISH_ID
        KUBE_NAMESPACE_PREFIX: dish-lmc-
      when: manual
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      variables:
        KUBE_NAMESPACE: "ci-$KUBE_APP-$DISH_ID-$CI_COMMIT_REF_NAME"
        KUBE_NAMESPACE_PREFIX: ci-dish-lmc-
        KUBE_NAMESPACE_POSTFIX: -$CI_COMMIT_REF_NAME
      when: manual

.dish-lmc:
  tags:
    - ska-k8srunner-za-itf
  extends:
    - .dish-env
  needs:
    - helm-chart-build
  allow_failure: true # need to keep this to unlock the pipeline
  environment:
    name: mid-itf/integration/$KUBE_NAMESPACE

.deploy-dish-lmc:
  stage: deploy-dish-aiv
  image: $DEPLOY_IMAGE
  before_script:
    - bash .make/resources/gitlab_section.sh vars "Print vars" make vars
  script:
    - bash .make/resources/gitlab_section.sh install "Install chart" make k8s-install-chart;
    - bash .make/resources/gitlab_section.sh wait "Wait for completion" make k8s-wait K8S_TIMEOUT=180s
  after_script:
    - make itf-dish-links
    - bash .make/resources/gitlab_section.sh template "Template chart" make k8s-template-chart
  extends:
    - .dish-lmc
    - .deploy_dish_rules
  environment:
    kubernetes:
      namespace: "$KUBE_NAMESPACE"
    url: https://$INGRESS_HOST/$KUBE_NAMESPACE/taranta/

.redeploy-dish-lmc:
  extends:
    - .deploy-dish-lmc
  script:
    - !reference [.uninstall-chart, script]
    - !reference [.deploy-dish-lmc, script]

.deploy-additional-lmc:
  extends:
    - .deploy-dish-lmc
  when: on_success

.deploy-dishlmc-ska063:
  extends:
    - .deploy-additional-lmc
  needs:
    - deploy-aa05-dishes
    - deploy-dishlmc-ska001
  variables:
    DISH_INDEX: "063"
  environment:
    on_stop: uninstall-dishlmc-ska063

.deploy-dishlmc-ska100:
  extends:
    - .deploy-additional-lmc
  needs:
    - deploy-aa05-dishes
    - deploy-dishlmc-ska001
  variables:
    DISH_INDEX: "100"
  environment:
    on_stop: uninstall-dishlmc-ska100

.destroy-dish-lmc:
  stage: deploy-dish-aiv
  extends:
    - .uninstall-chart
    - .dish-lmc
    - .uninstall_dish_rules
  environment:
    action: stop

.destroy-aa05-dishes:
  extends:
    - .destroy-dish-lmc
  when: on_success
  needs:
    - uninstall-aa05-dishes

include:
  - local: .gitlab/ci/za-itf/dish-lmc-skaXXX/ska001/.pipeline.yaml
  - local: .gitlab/ci/za-itf/dish-lmc-skaXXX/ska036/.pipeline.yaml
  # - local: .gitlab/ci/za-itf/dish-lmc-skaXXX/ska063/.pipeline.yaml
  # - local: .gitlab/ci/za-itf/dish-lmc-skaXXX/ska100/.pipeline.yaml

.uninstall-dishlmc-ska063:
  extends:
    - .destroy-aa05-dishes
  variables:
    DISH_ID: ska063

.uninstall-dishlmc-ska100:
  extends:
    - .destroy-aa05-dishes
  variables:
    DISH_ID: ska100
