# ############################
# # Dish AIV related CICD jobs
# ############################
.dish-env:
  variables:
    DISH_LMC_INITIAL_PARAMS: -f charts/dish-lmc/values.yaml --set global.dishes={$DISH_INDEX} --set global.raw_user_account=$CAR_RAW_USERNAME --set global.raw_user_pass=$CAR_RAW_PASSWORD
    CLUSTER_DOMAIN: miditf.internal.skao.int
    INGRESS_HOST: k8s.miditf.internal.skao.int
    K8S_CHART: dish-lmc
    KUBE_APP: dish-lmc
    DISH_ID: ska$DISH_INDEX

.dish_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        KUBE_NAMESPACE: $KUBE_APP-$DISH_ID
        KUBE_NAMESPACE_PREFIX: dish-lmc-
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      variables:
        KUBE_NAMESPACE: "ci-$KUBE_APP-$DISH_ID-$CI_COMMIT_REF_NAME"
        KUBE_NAMESPACE_PREFIX: ci-dish-lmc-
        KUBE_NAMESPACE_POSTFIX: -$CI_COMMIT_REF_NAME

.dish-lmc:
  tags:
    - ska-k8srunner-za-itf
  extends:
    - .dish_rules
    - .dish-env
  needs:
    - helm-chart-build
  allow_failure: true # need to keep this to unlock the pipeline
  environment:
    name: mid-itf/integration/$KUBE_NAMESPACE
    kubernetes:
      namespace: "$KUBE_NAMESPACE"
    url: https://$INGRESS_HOST/$KUBE_NAMESPACE/taranta/

.deploy-dish-lmc:
  stage: deploy-dish-aiv
  before_script:
    - bash .make/resources/gitlab_section.sh vars "Print vars" make vars
  script:
    - bash .make/resources/gitlab_section.sh install "Install chart" make k8s-install-chart && make k8s-wait K8S_TIMEOUT=90s
    - make itf-dish-links
  after_script:
    - bash .make/resources/gitlab_section.sh template "Template chart" make k8s-template-chart
    # - env
    # - bash .make/resources/gitlab_section.sh template "Template chart" make k8s-template-chart-with-build-artifacts # TEMPORARY COMMIT
  extends:
    - .dish-lmc

.redeploy-dish-lmc:
  extends:
    - .deploy-dish-lmc
  script:
    - !reference [.uninstall-chart, script]
    - !reference [.deploy-dish-lmc, script]

.deploy-additional-lmc:
  extends:
    - .deploy-dish-lmc
  when: on_success

deploy-dishlmc-ska001:
  extends:
    - .deploy-dish-lmc
  needs:
    - deploy-ds-sim-ska001
  when: always # TEMPORARY COMMIT
  # when: on_success # TEMPORARY COMMIT
  variables:
    DISH_INDEX: "001"
    DISH_LMC_EXTRA_PARAMS: -f charts/dish-lmc/values-cetc.yaml --set dishlmc.ska-mid-dish-ds-manager.dishstructuremanager.dsSim.fqdn=$DS_SIM_OPCUA_FQDN
  environment:
    on_stop: uninstall-dishlmc-ska001

redeploy-dishlmc-ska001:
  extends:
    - .redeploy-dish-lmc
  needs:
    - redeploy-ds-sim-ska001
  when: on_success
  variables:
    DISH_INDEX: "001"
    DISH_LMC_EXTRA_PARAMS: -f charts/dish-lmc/values-cetc.yaml --set dishlmc.ska-mid-dish-ds-manager.dishstructuremanager.dsSim.fqdn=$DS_SIM_OPCUA_FQDN
  environment:
    on_stop: uninstall-dishlmc-ska001

deploy-dishlmc-ska036:
  extends:
    - .deploy-additional-lmc
  needs:
    - deploy-dishlmc-ska001
    - deploy-aa05-dishes
  variables:
    DISH_INDEX: "036"
  environment:
    on_stop: uninstall-dishlmc-ska036

deploy-dishlmc-ska063:
  extends:
    - .deploy-additional-lmc
  needs:
    - deploy-aa05-dishes
    - deploy-dishlmc-ska001
  variables:
    DISH_INDEX: "063"
  environment:
    on_stop: uninstall-dishlmc-ska063

deploy-dishlmc-ska100:
  extends:
    - .deploy-additional-lmc
  needs:
    - deploy-aa05-dishes
    - deploy-dishlmc-ska001
  variables:
    DISH_LMC_INITIAL_PARAMS: -f charts/dish-lmc/values.yaml
    DISH_INDEX: "100"
  environment:
    on_stop: uninstall-dishlmc-ska100

.destroy-dish-lmc:
  stage: remove-dish-aiv
  extends:
    - .uninstall-chart
    - .dish-lmc
  environment:
    action: stop

.destroy-aa05-dishes:
  extends:
    - .destroy-dish-lmc
  when: on_success
  needs:
    - uninstall-aa05-dishes

uninstall-dishlmc-ska001:
  extends:
    - .destroy-dish-lmc
  needs:
    - remove-ds-sim-ska001
  variables:
    DISH_ID: ska001

uninstall-dishlmc-ska036:
  extends:
    - .destroy-aa05-dishes
  variables:
    DISH_ID: ska036

uninstall-dishlmc-ska063:
  extends:
    - .destroy-aa05-dishes
  variables:
    DISH_ID: ska063

uninstall-dishlmc-ska100:
  extends:
    - .destroy-aa05-dishes
  variables:
    DISH_ID: ska100
