---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ska-dish-ska010-archiver
  namespace: flux-services
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: ska-mid-itf
  path: ./datacentres/mid-itf/dish-lmc/deployment/ska-tango-archiver
  prune: true
  wait: true
  timeout: 5m0s
