
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../shared/deployment/ska-tango-archiver
  - vault_secrets.yml

patches:
  - path: helmrelease.yml
    target:
      kind: HelmRelease
      namespace: flux-services
