apiVersion: v2
name: ska-mid-icams-web-app-test
description: A Helm parent chart for the Tango Example
type: application
version: 0.1.0
appVersion: 0.1.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: ska-icams-web-app
  version: 1.2.1
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-web-s2i-flask-tango-panicapi
  version: 1.2.0
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-app-s2i-icams-scheduler
  version: 1.0.5
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tangogql
  version: 1.2.0
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tango-alarmhandler
  version: 0.6.1
  repository: https://artefact.skao.int/repository/helm-internal
