.deploy-icams:
  tags:
    - ska-k8srunner-za-itf
  stage: deploy-supplementary-services
  image: $DEPLOY_IMAGE
  variables:
    KUBE_APP: icams
    K8S_CHART: ska-mid-icams-web-app-test
    KUBE_NAMESPACE: icams-test
    HELM_RELEASE: icams-test
    K8S_SKIP_DEP_BUILD: "true"
  when: manual
  script:
    - make vars
    - export K8S_UMBRELLA_CHART_PATH=$(ls -t ./chart.tmp/ska-mid-icams-web-app-test-[0-9]*.tgz | head -n1)
    - sha256sum -c "$K8S_UMBRELLA_CHART_PATH.${CI_PIPELINE_ID}.sha256"
    - echo "Using chart archive - $K8S_UMBRELLA_CHART_PATH"
    - bash .make/resources/gitlab_section.sh install "K8S Install from .tgz" make k8s-install-chart
    - bash .make/resources/gitlab_section.sh wait "Wait for installation" make k8s-wait  
  needs:
    - job: helm-chart-build
      artifacts: true
  after_script:
    - rm -rf ./chart.tmp

.redeploy-icams:
  extends:
    - .deploy-icams
  before_script:
    - !reference [.uninstall-chart, script]
    - kubectl wait --for=delete namespace/$KUBE_NAMESPACE --timeout=60s

.destroy-icams:
  extends:
    - .deploy-icams
  script:
    - !reference [.uninstall-chart, script]
    - kubectl wait --for=delete namespace/$KUBE_NAMESPACE --timeout=60s

deploy-icams:
  extends:
    - .deploy-icams

redeploy-icams:
  extends:
    - .redeploy-icams

destroy-icams:
  extends:
    - .destroy-icams
