---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ska-tmc
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: ska-mid-itf
  path: ./datacentres/mid-itf/dish-lmc/deployment/podinfo2
  prune: true
  wait: true
  timeout: 5m0s
