---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo-dish-lmc
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: podinfo
      version: '6.5.*'
      sourceRef:
        kind: HelmRepository
        name: skatelescope
      interval: 5m
  releaseName: podinfo-dish-lmc
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  storageNamespace: podinfo-dish-lmc
  targetNamespace: podinfo-dish-lmc
  kubeConfig:
    secretRef:
      key: kubeconfig
      name: vault-miditf-dish-lmc-cluster-config
  values:
    replicaCount: 2
    global:
      