### TARANTA DEPLOYMENT
deploy-taranta:
  stage: platform
  tags:
    - ska-k8srunner-za-itf
  variables:
    KUBE_NAMESPACE: taranta
    KUBE_APP: ska-taranta-backend
    HELM_RELEASE: taranta
    K8S_CHART: taranta-itf
  script:
    - make k8s-install-chart
    - make k8s-wait
    - bash .make/resources/gitlab_section.sh template "Output deployment config information" make get-deployment-config-info
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_PIPELINE_ID"
    paths:
      - "build/"
  extends:
    - .integration_rules
