### TARANTA DEPLOYMENT
deploy-taranta:
  stage: platform
  tags:
    - k8srunner-za-itf-dishlmc-ska001
#    - ska-k8srunner-za-itf
  variables:
    KUBE_NAMESPACE: taranta
    KUBE_APP: ska-taranta-backend
    HELM_RELEASE: taranta
    K8S_CHART: taranta-itf
  script:
    - make k8s-install-chart
  extends:
    - .integration_rules
