### TARANTA DEPLOYMENT
deploy-taranta:
  stage: on_demand_itf_sut
  tags:
    - k8srunner-za-itf-dishlmc-ska001
#    - ska-k8srunner-za-itf
  variables:
    KUBE_NAMESPACE: taranta
    KUBE_APP: ska-taranta-backend
    HELM_RELEASE: taranta
    K8S_CHART: taranta-itf
    CLUSTER_DOMAIN: za-dish-lmc.skao.int
    MINIKUBE: "true"
  script:
    - make k8s-install-chart
    - make k8s-wait
  after_script:
    - bash .make/resources/gitlab_section.sh template "Template Chart" make k8s-template-chart-with-build-artifacts
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_PIPELINE_ID"
    paths:
      - "build/"
  extends:
    - .on_demand_rules
