apiVersion: v2
appVersion: 0.6.2
dependencies:
- name: ska-tango-util
  repository: https://artefact.skao.int/repository/helm-internal
  version: 0.3.14
- condition: ska-tango-base.enabled,global.sub-system.ska-tango-base.enabled
  name: ska-tango-base
  repository: https://artefact.skao.int/repository/helm-internal
  version: 0.3.14
description: A Helm chart for Tango controls of test equipment
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
name: ska-ser-test-equipment
type: application
version: 0.6.2
