# FROM artefact.skao.int/ska-tango-images-pytango-builder:9.3.32 AS buildenv
# RUN apt-get update && apt-get install gnupg2 -y

ARG BUILD_IMAGE="artefact.skao.int/ska-tango-images-pytango-builder:9.3.32"
ARG BASE_IMAGE="artefact.skao.int/ska-tango-images-pytango-runtime:9.3.19"
FROM $BUILD_IMAGE AS buildenv
FROM $BASE_IMAGE

USER root

RUN apt-get update && apt-get install gnupg2 gawk git vim -y
RUN poetry config virtualenvs.create false

WORKDIR /app
COPY --chown=tango:tango . /app

RUN pip install --upgrade poetry
RUN poetry install

USER tango

RUN poetry config virtualenvs.create false
RUN poetry shell && poetry install

ENTRYPOINT [ "/bin/bash" ]
