ska-tmc-mid:
  telescope: SKA-mid
  deviceServers:
    centralnode:
      subarray_count: 1
      DishVccConfig:
        DishVccUri: "car://gitlab.com/ska-telescope/ska-telmodel-data?0.1.0-rc-mid-itf#tmdata"
        DishVccFilePath: "instrument/ska1_mid_itf/ska-mid-cbf-system-parameters.json"
    cspsubarrayleafnode:
      TelmodelSource: "gitlab://gitlab.com/ska-telescope/ska-mid-itf?main#tmdata"
      TelmodelPath: "instrument/ska1_mid_itf/layout/aa05-zerodelay-itf-layout.json"
