apiVersion: v2
name: taranta-itf
description: An umbrella Helm chart for deploying Taranta charts that are not the application itself - we need only a single deployment for the cluster
type: application
version: 0.1.0
appVersion: 0.1.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: ska-tango-base
  version: 0.4.7
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-tango-base.enabled
- name: ska-tango-taranta-dashboard
  version: 1.5.0
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-tango-taranta-dashboard.enabled
- name: ska-tango-taranta-dashboard-pvc
  version: 1.5.0
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-tango-taranta-dashboard.enabled
- name: ska-tango-taranta
  version: 2.6.0
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tango-tangogql
  version: 1.3.10
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tango-taranta-auth
  version: 0.2.0
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-tango-taranta-auth.enabled


# TARANTA THINGS
#  - name: ska-tango-taranta-auth
#    version: 0.2.0
#    repository: https://artefact.skao.int/repository/helm-internal
#    condition: global.taranta_auth_enabled
#  - name: ska-tango-taranta-dashboard
#    version: 1.5.0
#    repository: https://artefact.skao.int/repository/helm-internal
#    condition: global.taranta_dashboard_enabled
#  - name: ska-tango-taranta-dashboard-pvc
#    version: 1.5.0
#    repository: https://artefact.skao.int/repository/helm-internal
#    condition: global.taranta_dashboard_enabled
