apiVersion: v2
name: taranta-itf
description: An umbrella Helm chart for deploying Taranta charts that are not the application itself - we need only a single deployment for the cluster
type: application
version: 0.1.0
appVersion: 0.1.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  # TARANTA THINGS
  - name: ska-tango-taranta-auth
    version: 0.2.0 # change to 0.2.2
    repository: https://artefact.skao.int/repository/helm-internal
    condition: global.taranta_auth_enabled
  - name: ska-tango-taranta-dashboard
    version: 1.5.0 # change to 1.6.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: global.taranta_dashboard_enabled
  - name: ska-tango-taranta-dashboard-pvc
    version: 1.6.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: global.taranta_dashboard_enabled
