# TANGOGQL
tangogql:
  tangoDB: environment-dish-lmc-dishid # environment should be `staging` or `integration`, dishid should be set in makefile
  enabled: true
  ska-tango-base:
    enabled: false
  ska-tango-examples:
    enabled: false
