---
debug: false

# This is a mapping of host groups to user groups:
# users will be created with these user groups on the hosts within the host group.
# The first group in the user group list is the user's primary group.
user_groups_by_host_group:
  raspberry_pi:
    - name: atlas
      create: true
    - name: sudo
      create: false
  test:
    - name: atlas
      create: true
    - name: sudo
      create: false

add_to_sudoers:
  raspberry_pi: true
  test: true

createuser: false
removeuser: false
