.test-upgrade-rules:
  rules:
    # - if: '$CI_COMMIT_BRANCH == "main"' TODO: revert to only main
    #   when: manual
    - when: manual
      allow_failure: true
    - when: never

test-upgradability:
  stage: upgrade
  extends:
    - .staging-env
    - .test-end-to-end-with-hw
    - .test-upgrade-rules
  variables:
    DISH_IDS: "SKA063"
    INTEGRATION_TEST_SOURCE: tests/integration/tmc/test_upgradability.py::test_upgrade_path
    KUBE_NAMESPACE_PREFIX: "staging-dish-lmc-" 
  script:
    - SKA_MID_SITE_CHART_VERSION=$(bash .gitlab/ci/za-itf/upgrading/get_site_version.sh)
    - export SKA_MID_SITE_CHART_VERSION
    - echo "ska-mid chart version from ska-mid-helmreleases main - ${SKA_MID_SITE_CHART_VERSION}"
    - make integration-test
    - '[ -f build/status ] || (echo "Something went wrong with the test (no build/status file); exit 1")'
    - exit $(cat build/status)
