# DISH SKA001 SPECIFIC CI

.ska001-env:
  variables:
    DISH_ID: ska001
    DISH_INDEX: "001"
    SPFRX_TANGO_INSTANCE: rxpu-1
    SPFRX_ADDRESS: 10.165.3.20
    SPFRX_IN_THE_LOOP: "false"
    SPFC_IN_THE_LOOP: "false"
    SPFC_INSTANCE: spfc-devkit
    # Remember to explicitly quote the URL to prevent parsing errors
    DISH_LMC_EDA_PARAMS: '--set ska-tango-archiver.configuration_file_url="https://gitlab.com/ska-telescope/ska-mid-itf/-/raw/26.1.1/tmdata/mid-itf-staging-archiver-configs/dish-lmc-ska001.yaml?ref_type=tags&inline=false"'

1-deploy-dishlmc-ska001:
  extends:
    - .deploy-dish-lmc
    - .ska001-env
  ### TEMPORARILY DISABLED DEPLOYMENT OF DS-SIM - SEE .gitlab/ci/za-itf/ds-sim-skaXXX/.pipeline.yaml
  # needs:
  #   - deploy-ds-sim-ska001
  # when: on_success
  # variables:
  #   DISH_LMC_EXTRA_PARAMS: -f charts/ska-mid/values-cetc.yaml --set ska-dish-lmc.ska-mid-dish-ds-manager.dishstructuremanager.dsSim.fqdn=$DS_SIM_OPCUA_FQDN
  when: manual
  environment:
    on_stop: 1-uninstall-dishlmc-ska001

1-redeploy-dishlmc-ska001:
  extends:
    - .redeploy-dish-lmc
    - .ska001-env
  when: manual
  # variables:
  #   DISH_LMC_EXTRA_PARAMS: -f charts/ska-mid/values-cetc.yaml --set ska-dish-lmc.ska-mid-dish-ds-manager.dishstructuremanager.dsSim.fqdn=$DS_SIM_OPCUA_FQDN
  environment:
    on_stop: 1-uninstall-dishlmc-ska001

1-uninstall-dishlmc-ska001:
  extends:
    - .destroy-dish-lmc
    - .ska001-env
