apiVersion: v2
name: ska-mid-itf
description: An umbrella Helm chart for deployment of the System Under Test at the Mid ITF
type: application
version: 0.1.0
appVersion: 0.1.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  - name: ska-tango-base
    version: 0.4.7
    repository: https://artefact.skao.int/repository/helm-internal

  - name: ska-tango-util
    version: 0.4.7
    repository: https://artefact.skao.int/repository/helm-internal

  # SKA Mid Software
  - name: ska-mid-cbf-mcs
    version: 0.11.0
    repository: https://artefact.skao.int/repository/helm-internal
    alias: cbf-mcs
    condition: cbf-mcs.enabled

  - name: ska-mid-cbf-tmleafnode
    version: 0.11.0
    repository: https://artefact.skao.int/repository/helm-internal
    alias: cbf-tmleafnode
    condition: cbf-tmleafnode.enabled

  - name: ska-tmc-mid
    version: 0.12.0 # check latest version
    repository: https://artefact.skao.int/repository/helm-internal
    alias: tmc
    condition: test-equipment.enabled

  - name: ska-csp-lmc-mid
    version: 0.16.5 # check latest version
    repository: https://artefact.skao.int/repository/helm-internal
    alias: csp-lmc
    condition: test-equipment.enabled

  - name: ska-sdp
    version: 0.17.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-sdp.enabled

  # Temporarily deploy Dish LMC in SUT because TMC doesn't currently support an external Dish LMC
  - name: ska-dish-lmc
    version: 2.5.0
    repository: https://artefact.skao.int/repository/helm-internal
    alias: dishlmc

  # SKA Configuration Inspector API
  # Gitlab Location: https://gitlab.com/ska-telescope/ska-ser-config-inspector
  # Releases: https://gitlab.com/ska-telescope/ska-ser-config-inspector/-/releases
  # - name: ska-k8s-exporter
  #   version: 0.1.0 # check latest version
  #   repository: https://artefact.skao.int/repository/helm-internal
  #   condition: cia.enabled

  # TARANTA SUITE
  - name: ska-tango-taranta
    version: 2.2.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled

  - name: ska-tango-tangogql
    version: 1.3.8
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled

  # test helpers
  - name: ska-log-consumer
    version: 0.1.6
    repository: https://artefact.skao.int/repository/helm-internal
