apiVersion: v2
name: ska-mid-itf
description: An umbrella Helm chart for deployment of the System Under Test at the Mid ITF
type: application
version: 23.1.1
appVersion: 23.1.1
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  # Tango Base & Deployment Charts: TangoDB, iTango, Tango Operator Utils
  - name: ska-tango-base
    version: 0.4.10
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tango-util
    version: 0.4.11
    repository: https://artefact.skao.int/repository/helm-internal

  # SKA Mid TMC
  - name: ska-tmc-mid
    version: 0.20.0 # check latest version
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tmc-mid.enabled

  # SKA Mid CSP LMC
  - name: ska-csp-lmc-mid
    version: 0.20.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-csp-lmc-mid.enabled

  # SKA Mid CBF
  - name: ska-mid-cbf-mcs
    version: 0.15.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-mid-cbf-mcs.enabled

  - name: ska-mid-cbf-engineering-console
    version: 0.10.8
    repository: https://artefact.skao.int/repository/helm-internal

  # SKA Mid SDP
  - name: ska-sdp
    version: 0.21.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-sdp.enabled

  # SKA Configuration Inspector API
  # Gitlab Location: https://gitlab.com/ska-telescope/ska-ser-config-inspector
  # Releases: https://gitlab.com/ska-telescope/ska-ser-config-inspector/-/releases
  - name: ska-ser-config-inspector
    version: 0.2.3 # check latest version
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-ser-config-inspector.enabled

  # TARANTA SUITE
  - name: ska-tango-taranta
    version: 2.10.2
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
  - name: ska-tango-tangogql
    version: 1.4.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled

  # test helpers
  - name: ska-log-consumer
    version: 0.1.6
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-log-consumer.enabled

  # SKA Tango AlarmHandler
  - name: ska-tango-alarmhandler
    version: 0.4.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-alarmhandler.enabled

  # EDA
  - name: ska-tango-archiver
    version: 2.7.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-archiver.enabled

  # EXAMPLE DEV CHART: DON'T DELETE THIS SECTION
  # - name: ska-sdp
  #   version: 0.19.0-dev.c651132b9
  #   repository: https://gitlab.com/api/v4/projects/21141217/packages/helm/dev
