ska-tango-archiver: # FIXME: also see global section
  enabled: false

global:
  ska-tango-archiver:
    enabled: false
  # Used by TMC dishleafnode for Dish LMC device identifier triplet.
  # The TMC centralnode's values are hardocoded at the moment.
  dish_suffix: "elt/master"
  minikube: false
  tango_host: tango-databaseds:10000
  facility: mid-itf
  operator: true
  exposeAllDS: true
  data-product-pvc-name: test-pvc
  sub-system:
    ska-tango-base:
      enabled: false

ska-tango-base:
  itango:
    enabled: true

# TARANTA
ska-taranta:
  enabled: true
  tangogql:
    replicas: 1
    resources:
      requests:
        cpu: 600m # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem

# CIA
cia:
  enabled: false

cbf-mcs:
  enabled: true
  engineeringConsoleVersion: 0.9.1
  signalVerificationVersion: 0.2.4
  hostInfo:
    environment: "mid-itf"
    clusterDomain: "miditf.internal.skao.int"

csp-lmc:
  legacy_compatibility: true
  enabled: true

### tmc - also see tmc-values for DishIDs!
tmc:
  legacy_compatibility: true
  enabled: true
  telescope: SKA-mid
  global:
    Dish:
      isSimulated:
        enabled: false
    subarray_count: 1
  deviceServers:
    centralnode:
      subarray_count: 1
    dishleafnode:
      enabled: true
  ska-tango-base:
    enabled: false

sdp:
  legacy_compatibility: true
  enabled: false
  lmc:
    prefix: mid
    nsubarray: 3
  console:
    enabled: true
  data-pvc:
    create:
      enabled: true
      size: 20Gi
      storageClassName: nfss1
  ska-sdp-qa:
    kafka:
      resources:
        limits:
          cpu: 750m
          memory: 1024Mi
        requests:
          cpu: 250m
          memory: 500Mi
      livenessProbe:
        initialDelaySeconds: 30
        failureThreshold: 5
      zookeeper:
        resources:
          requests:
            cpu: 100m
  ska-tango-base:
    enabled: false

# helpers
ska-log-consumer:
  enabled: false

# EDA
ska-tango-archiver:
  hostname: eda.ska-tango-archiver
  dbname: itf_eda
  dbuser: admin
  password: bkS3OD0w9HnibRo_7d3nq1hT
  port: 5432
  telescope: SKA-mid
  telescope_environment: MID-ITF
  configuration_manager: mid-eda/cm/01
  event_subscriber: mid-eda/es/01
  archwizard_config: MyHDB=tango://tango-databaseds:10000/mid-eda/cm/01

archviewer:
  instances:
  - name: ""
    timescale_host: "tango-databaseds.ci-ska-mid-itf-at-1807-eda-integration-v2.svc.miditf.internal.skao.int:10000/mid-eda/cm/01"
    #keep below field empty if db names are unknown, app will display all dbs present
    #e.g:timescale_databases: ""    
    timescale_databases: "itf-eda" 
    timescale_login: "admin:bkS3OD0w9HnibRo_7d3nq1hT"
 