global:
  dishes: ["001", "002", "003", "004"] # Temporary Dish LMC configuration
  dish_suffix: "elt/master"
  dish_prefix: "elt/master"
  minikube: true
  tango_host: tango-databaseds:10000
  facility: test-itf
  operator: true
  exposeAllDS: true
  data-product-pvc-name: test-pvc
  sub-system:
    ska-tango-base:
      enabled: false

ska-tango-base:
  itango:
    enabled: true

# TARANTA
ska-taranta:
  enabled: true
  tangogql:
    replicas: 1
    resources:
      requests:
        cpu: 600m # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem

# CIA
cia:
  enabled: false

cbf-mcs:
  enabled: true
  engineeringConsoleVersion: 0.8.3
  signalVerificationVersion: 0.1.11
  hostInfo:
    environment: "mid-itf"
    clusterDomain: "miditf.internal.skao.int"


cbf-tmleafnode:
  enabled: false

ska-csp-lmc-mid:
  legacy_compatibility: true
  enabled: true

### tmc
tmc-mid:
  legacy_compatibility: true
  enabled: true
  telescope: SKA-mid


ska-sdp:
  legacy_compatibility: true
  enabled: true
  lmc:
    prefix: mid
    nsubarray: 3
  console:
    enabled: true
  data-pvc:
    create:
      enabled: true
      size: 20Gi
      storageClassName: nfss1
  ska-sdp-qa:
    kafka:
      resources:
        limits:
          cpu: 750m
          memory: 1024Mi
        requests:
          cpu: 250m
          memory: 500Mi
      livenessProbe:
        initialDelaySeconds: 30
        failureThreshold: 5
      zookeeper:
        resources:
          requests:
            cpu: 100m
  ska-tango-base:
    enabled: false

# Temporarily deploy Dish LMC in SUT because TMC doesn't currently support an external Dish LMC
dishlmc:
  ska-mid-dish-manager:
    legacy_compatibility: true
    ska-mid-dish-simulators:
      enabled: true
      legacy_compatibility: true
      ska-tango-base:
        enabled: false
      deviceServers:
        spfdevice:
          enabled: true
        spfrxdevice:
          enabled: true

# helpers
ska-log-consumer:
  enabled: false
