ska-tango-archiver: # FIXME: also see global section
  enabled: false

global:
  ska-tango-archiver:
    enabled: false
  # Used by TMC dishleafnode for Dish LMC device identifier triplet.
  # The TMC centralnode's values are hardocoded at the moment.
  dish_suffix: "elt/master"
  minikube: false
  tango_host: tango-databaseds:10000
  facility: mid-itf
  operator: true
  exposeAllDS: true
  data-product-pvc-name: test-pvc
  sub-system:
    ska-tango-base:
      enabled: false

ska-tango-base:
  itango:
    enabled: true

# TARANTA
ska-taranta:
  enabled: true
  tangogql:
    replicas: 1
    resources:
      requests:
        cpu: 600m # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem

# CIA
cia:
  enabled: false

cbf-mcs:
  enabled: true
  engineeringConsoleVersion: 0.9.15
  signalVerificationVersion: 0.2.13
  hostInfo:
    environment: "mid-itf"
    clusterDomain: "miditf.internal.skao.int"

cbf-tmleafnode:
  enabled: false

csp-lmc:
  legacy_compatibility: true
  enabled: true

### tmc - also see tmc-values for DishIDs!
tmc:
  legacy_compatibility: true
  enabled: true
  telescope: SKA-mid
  global:
    subarray_count: 1
  deviceServers:
    mocks:
      enabled: false
      is_simulated:
        csp: false
        sdp: false
        dish: false
    centralnode:
      subarray_count: 1
    dishleafnode:
      enabled: true
  ska-tango-base:
    enabled: false

sdp:
  helmdeploy:
    enableNADClusterRole: true
  legacy_compatibility: true
  enabled: true
  lmc:
    prefix: mid
    nsubarray: 3
  data-pvc:
    create:
      enabled: true
      size: 20Gi
      storageClassName: nfss1
  ska-tango-base:
    enabled: false

# helpers
ska-log-consumer:
  enabled: false
