global:
  ska-tango-archiver:
    enabled: true
  # Used by TMC dishleafnode for Dish LMC device identifier triplet.
  # The TMC centralnode's values are hardocoded at the moment.
  dish_suffix: "elt/master"
  minikube: false
  tango_host: tango-databaseds:10000
  facility: mid-itf
  operator: true
  exposeAllDS: true
  data-product-pvc-name: test-pvc
  use_aws: true
  sub-system:
    ska-tango-base:
      enabled: false

ska-tango-base:
  itango:
    enabled: true
  tangodb:
    use_pv: true

# TARANTA
ska-taranta:
  enabled: true
  tangogql:
    replicas: 1
    resources:
      requests:
        cpu: 600m # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem

# CIA
ska-ser-config-inspector:
  enabled: true

ska-mid-cbf-mcs:
  enabled: true
  engineeringConsoleVersion: 0.10.2
  hostInfo:
    environment: "mid-itf"
    clusterDomain: "miditf.internal.skao.int"


ska-mid-cbf-tmleafnode:
  enabled: true

ska-csp-lmc-mid:
  legacy_compatibility: true
  enabled: true

### tmc - also see tmc-values for DishIDs!
ska-tmc-mid:
  legacy_compatibility: true
  enabled: true
  telescope: SKA-mid
  global:
    subarray_count: 1
  deviceServers:
    mocks:
      enabled: false
      csp: false
      sdp: false
      dish: false
    centralnode:
      subarray_count: 1
    dishleafnode:
      enabled: true
  ska-tango-base:
    enabled: false
  resources:
    limits:
      cpu: 800m
    requests:
      cpu: 400m


ska-sdp:
  helmdeploy:
    enableNADClusterRole: true
  legacy_compatibility: true
  enabled: true
  lmc:
    prefix: mid
    nsubarray: 3
  data-pvc:
    create:
      enabled: false
  ska-tango-base:
    enabled: false

# helpers
ska-log-consumer:
  enabled: false

# EDA
ska-tango-archiver:
  enabled: true
  hostname: eda.ska-tango-archiver
  dbname: itf_eda
  dbuser: admin
  port: 5432
  telescope: SKA-mid
  telescope_environment: MID-ITF
  configuration_manager: mid-eda/cm/01
  event_subscriber: mid-eda/es/01
  archwizard_config: MyHDB=tango://tango-databaseds:10000/mid-eda/cm/01
  archviewer:
    instances:
    - name: "mid"
      timescale_host: "10.164.11.33"
  #     #keep below field empty if db names are unknown, app will display all dbs present
  #     #e.g:timescale_databases: ""  
      timescale_databases: "itf_eda"

# Temporary configuration for PVC
# See templates/pvc.yaml
temp_sdp_pvc:
  dpd_namespace: ska-dpd
  dpd_pvc: shared-mnl
