global:
  minikube: true
  tango_host: tango-databaseds:10000
  facility: test-itf
  operator: false
  cluster_domain: "miditf.internal.skao.int"
  exposeAllDS: true
  sub-system:
    ska-tango-base:
      enabled: false

ska-tango-base:
  itango:
    enabled: true

# TARANTA
ska-taranta:
  enabled: true
  tangogql:
    replicas: 1
    resources:
      requests:
        cpu: 600m # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem

# CIA
cia:
  enabled: false

cbf-mcs:
  enabled: true
  engineeringConsoleVersion: 0.8.3
  signalVerificationVersion: 0.1.11
  hostInfo:
    environment: "mid-itf"
    clusterDomain: "miditf.internal.skao.int"


cbf-tmleafnode:
  enabled: false

ska-csp-lmc-mid:
  legacy_compatibility: true
  enabled: true
#  cluster_domain: "miditf.internal.skao.int"
#  operator: false

### tmc
tmc-mid:
  legacy_compatibility: true
  enabled: true
  telescope: SKA-mid

# helpers
ska-log-consumer:
  enabled: false
