apiVersion: v2
name: tango-base-util
description: An umbrella Helm chart for ska-tango-base and ska-tango-util for SUT and TE deployments.
type: application
version: 0.1.0
appVersion: 0.1.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  - name: ska-tango-base
    version: 0.4.7
    repository: https://artefact.skao.int/repository/helm-internal

  - name: ska-tango-util
    version: 0.4.11-dev.c921857f5
    repository: https://gitlab.com/api/v4/projects/9027158/packages/helm/dev
