kind: ConfigMap
apiVersion: v1
metadata:
  name: chartinfo-{{ .Release.Name }}
data:
  chartinfo.json: |-
    {
        "name": "{{ .Chart.Name }}",
        "version": "{{ .Chart.Version }}",
        "release": "{{ .Release.Name }}",
        "dependencies": [
        {{- $last := sub (len .Chart.Dependencies) 1 }}
        {{- range $index, $item := .Chart.Dependencies }}
        { "name": "{{ $item.Name }}" , "version": "{{ $item.Version }}" }{{ if ne $index $last }},{{ end }}
        {{- end }}
        ]
    }
