kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: {{ index .Values.global "data-product-pvc-name" }}
    namespace: {{ .Release.Namespace }}
    labels:
        skao.int/clone-pvc: shared-mnl
        skao.int/clone-pvc-namespace: ci-ska-mid-itf-dpd-at-1916
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 2Ti
    storageClassName: ceph-cephfs
    volumeMode: Filesystem
status:
    accessModes:
        - ReadWriteMany
    capacity:
        storage: 2Ti
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: {{ index .Values.global "data-product-pvc-name" }}
    namespace: {{ .Release.Namespace }}-sdp
    labels:
        skao.int/clone-pvc: shared-mnl
        skao.int/clone-pvc-namespace: ci-ska-mid-itf-dpd-at-1916
spec:
    storageClassName: ceph-cephfs
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 2Ti
status:
    accessModes:
        - ReadWriteMany
    capacity:
        storage: 2Ti
