.dpd:
  tags:
    - ska-k8srunner-za-itf
  variables:
    CONFIG: mid
    K8S_CHART: ska-mid-itf-dpd
    KUBE_APP: ska-mid-itf-dpd
    KUBE_NAMESPACE_SDP: "ci-ska-mid-itf-$CI_COMMIT_REF_NAME-sdp"
    INGRESS_HOST: "k8s.miditf.internal.skao.int"
    CLUSTER_DOMAIN: "miditf.internal.skao.int"
    MINIKUBE: "false"
  environment:
    name: sut/dpd/$KUBE_NAMESPACE
    kubernetes:
      namespace: $KUBE_NAMESPACE
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/dashboard/"
  when: manual
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_PIPELINE_ID"
    paths:
      - "build/"

.dpd-on-demand:
  extends:
    - .dpd
    - .on_demand_rules
  stage: on_demand_itf_sut
  when: always # TEMPORARY COMMIT
  variables:
    KUBE_NAMESPACE: ci-ska-mid-itf-dpd-$CI_COMMIT_REF_NAME

.dpd-install:
  script:
    - make vars
    - bash .make/resources/gitlab_section.sh install "Install chart" make k8s-install-chart
    - bash .make/resources/gitlab_section.sh wait "Wait for installation" make k8s-wait
    - helm version
    - helm get all -n $KUBE_NAMESPACE $HELM_RELEASE || true
  after_script:
    - make dpd-links
    - bash .make/resources/gitlab_section.sh template "Template chart" make k8s-template-chart-with-build-artifacts
    - bash .make/resources/gitlab_section.sh helmget "Get all Helm configuration data" helm get all -n $KUBE_NAMESPACE $HELM_RELEASE

.dpd-destroy:
  script:
    - !reference [.cleanup, script]
  environment:
    action: stop

.dpd-redeploy:
  extends:
    - .dpd-install
  before_script:
    - !reference [.cleanup, script]

deploy-dpd-on-demand:
  extends:
    - .dpd-on-demand
    - .dpd-install
  environment:
    on_stop: destroy-dpd-on-demand

redeploy-dpd-on-demand:
  extends:
    - .dpd-on-demand
    - .dpd-redeploy
  environment:
    on_stop: destroy-dpd-on-demand

destroy-dpd-on-demand:
  extends:
    - .dpd-on-demand
    - .dpd-destroy

.dpd-staging:
  extends:
    - .dpd
    - .staging_rules
  stage: staging
  variables:
    KUBE_NAMESPACE: ska-dpd-staging
    KUBE_NAMESPACE_SDP: staging-sdp
    DPD_PVC_NAME: staging-pvc

deploy-dpd-staging:
  extends:
    - .dpd-staging
    - .dpd-install
  environment:
    on_stop: destroy-dpd-staging

destroy-dpd-staging:
  extends:
    - .dpd-staging
    - .dpd-destroy

redeploy-dpd-staging:
  extends:
    - .dpd-staging
    - .dpd-redeploy
  environment:
    on_stop: destroy-dpd-staging
