apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: integration-tests
spec:
  backoffLimit: 0
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    spec:
      volumes:
      - name: test-data-storage
        persistentVolumeClaim:
          claimName: {{ .Values.testReportsPVC }}
      initContainers:
      - name: test-smoke
        image: {{ .Values.image.registry }}/{{ .Values.image.image }}:{{ .Values.image.tag }}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        volumeMounts:
        - name: test-data-storage
          mountPath: {{ .Values.mountPath }}
        - name: cbf-ec-clone-pvc
          mountPath: /app/cbf-ec
        - name: talon-hw-config-volume
          mountPath: {{ .Values.CBFMCSconfigMountPath }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command: ["sh", "-c"]
        args:
        - |
          TEST_REPORT_DIR="{{ .Values.mountPath }}/$(date +'%Y-%m-%d_%H-%M-%S')"
          mkdir -p "$TEST_REPORT_DIR"
          echo "$TEST_REPORT_DIR" > {{ .Values.mountPath }}/test_report_dir.txt
          . .venv/bin/activate
          export PYTHONPATH=/app/ska-mid/.venv/lib/python3.10/site-packages:$PYTHONPATH
          python3 -m pytest tests/smoke/ \
          --log-cli-level=DEBUG \
          --log-file="$TEST_REPORT_DIR/$(date +'%Y-%m-%d_%H-%M-%S')_test-smoke" 2>&1
      containers:
      - name: test-end-to-end
        image: {{ .Values.image.registry }}/{{ .Values.image.image }}:{{ .Values.image.tag }}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        volumeMounts:
        - name: test-data-storage
          mountPath: {{ .Values.mountPath }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        {{- range $key, $value := .Values.environment }}
          - name: {{ $key }}
            value: "{{ $value }}"
        {{- end }}
        command: ["sh", "-c"]
        args:
        - |
          TEST_REPORT_DIR=$(cat {{ .Values.mountPath }}/test_report_dir.txt)
          . .venv/bin/activate
          export PYTHONPATH=/app/ska-mid/.venv/lib/python3.10/site-packages:$PYTHONPATH
          python3 -m pytest tests/integration/tmc/test_end_to_end.py::test_e2e_via_tmc \
          --log-cli-level=DEBUG \
          --log-file="$TEST_REPORT_DIR/$(date +'%Y-%m-%d_%H-%M-%S')_test-end-to-end.log" 2>&1
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}