apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: integration-tests
spec:
  backoffLimit: 1
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    spec:
      volumes:
      - name: test-data-storage
        persistentVolumeClaim:
          claimName: {{ .Values.test_reports_pvc }}
      initContainers:
      - name: test-smoke
        image: {{ .Values.image.registry }}/{{ .Values.image.image }}:{{ .Values.image.tag }}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        volumeMounts:
        - name: test-data-storage
          mountPath: {{ .Values.mountPath }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command: ["sh", "-c"]
        args:
        - |
          . .venv/bin/activate \
          python3 -m pytest tests/smoke/ \
          --log-cli-level=DEBUG \
          --log-file="{{ .Values.mountPath }}/$(date +'%Y-%m-%d_%H-%M-%S')_test-smoke" 2>&1
      containers:
      - name: test-end-to-end
        image: {{ .Values.image.registry }}/{{ .Values.image.image }}:{{ .Values.image.tag }}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        volumeMounts:
        - name: test-data-storage
          mountPath: {{ .Values.mountPath }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        {{- range $key, $value := .Values.environment }}
          - name: {{ $key }}
            value: "{{ $value }}"
        {{- end }}
        command: ["sh", "-c"]
        args:
        - |
          . .venv/bin/activate
          pytest tests/integration/tmc/test_end_to_end.py::test_e2e_via_tmc \
          --log-cli-level=DEBUG \
          --log-file="{{ .Values.mountPath }}/$(date +'%Y-%m-%d_%H-%M-%S')_test-end-to-end.log" 2>&1
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}