apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: integration-tests
spec:
  backoffLimit: 1
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    spec:
      volumes:
      - name: test-data-storage
        persistentVolumeClaim:
          claimName: pvc-test-data-storage
      initContainers:
      - name: test-smoke
        image: registry.gitlab.com/ska-telescope/ska-mid-itf/ska-mid-itf:26.2.0-dev.cbf8f5714
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: test-data-storage
          mountPath: /data/test-reports
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command: ["sh", "-c"]
        args:
        - |
          . .venv/bin/activate \
          python3 -m pytest tests/smoke/ \
          --log-cli-level=DEBUG \
          --log-file="/data/test-reports/$(date +'%Y-%m-%d_%H-%M-%S')_test-smoke" 2>&1
      containers:
      - name: test-end-to-end
        image: registry.gitlab.com/ska-telescope/ska-mid-itf/ska-mid-itf:26.2.0-dev.cbf8f5714
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: test-data-storage
          mountPath: /data/test-reports
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: SIM_MODE
          value: "true"
        - name: E2E_TEST_EXECUTION_NAMESPACE
          value: "ska-mid-central-controller"
        - name: KUBE_NAMESPACE
          value: "ska-mid-central-controller"
        - name: SUT_CLUSTER_DOMAIN
          value: "mid.internal.skao.int"
        - name: DISH_IDS
          value: "SKA001"
        command: ["sh", "-c"]
        args:
        - |
          . .venv/bin/activate
          pytest tests/integration/tmc/test_end_to_end.py::test_e2e_via_tmc \
          --log-cli-level=DEBUG \
          --log-file="/data/test-reports/$(date +'%Y-%m-%d_%H-%M-%S')_test-end-to-end.log" 2>&1
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}