apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-data-storage
  namespace: integration-tests
spec:
  storageClassName: ceph-cephfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi