apiVersion: v1
kind: Pod
metadata:
  name: test-reports-reader
  namespace: integration-tests
spec:
  volumes:
  - name: test-data-storage
    persistentVolumeClaim:
      claimName: pvc-test-data-storage
  containers:
  - image: registry.gitlab.com/ska-telescope/ska-mid-itf-engineering-tools/ska-mid-itf-engineering-tools:0.9.3
    name: pod
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
    - name: test-data-storage
      mountPath: /data/test-reports
    env:
    - name: SIM_MODE
      value: "true"
    - name: E2E_TEST_EXECUTION_NAMESPACE
      value: "integration"
    - name: KUBE_NAMESPACE
      value: "integration"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}