apiVersion: v1
kind: Pod
metadata:
  name: test-reports-reader
  namespace: integration-tests
spec:
  volumes:
  - name: test-data-storage
    persistentVolumeClaim:
      claimName: pvc-test-data-storage
  containers:
  - image: {{ .Values.image.registry }}/{{ .Values.image.image }}:{{ .Values.image.tag }}
    name: pod
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
    - name: test-data-storage
      mountPath: {{ .Values.mountPath }}
    env:
    - name: SIM_MODE
      value: "true"
    - name: E2E_TEST_EXECUTION_NAMESPACE
      value: "integration"
    - name: KUBE_NAMESPACE
      value: "integration"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}