apiVersion: v1
kind: Pod
metadata:
  name: test-reports-reader
  namespace: integration-tests
spec:
  volumes:
  - name: test-data-storage
    persistentVolumeClaim:
      claimName: pvc-test-data-storage
  containers:
  - image: {{ .Values.image.registry }}/{{ .Values.image.image }}:{{ .Values.image.tag }}
    name: test-reports-reader
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
    - name: test-data-storage
      mountPath: {{ .Values.mountPath }}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}