---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ska-mid-dish
  namespace: flux-services
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ska-mid-itf-dish-lmc
      version: '24.3.1-dev.cfb7b6d53'
      sourceRef:
        kind: HelmRepository
        name: ska-mid-itf-git
  releaseName: ska-mid-itf-dish-lmc-skaxxx
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      strategy: "uninstall"
      retries: 3
  storageNamespace: ska-mid-itf-dish-lmc-skaxxx
  targetNamespace: ska-mid-itf-dish-lmc-skaxxx
  valuesFrom:
  - kind: Secret
    name: vault-shared-dish
    valuesKey: values.yml
      