"ska-tmc-mid":
  "deviceservers":
    "centralnode":
      "dishids":
      - "SKA420"
    "dishleafnode":
      "instances":
      - "420"
    "subarraynode":
      "dishids":
      - "SKA420"
  "global":
    "namespace_dish":
      "dish_names":
      - "tango://tango-databaseds.dish-lmc-ska420.svc.ska420.miditf.internal.skao.int:10000/mid-dish/dish-manager/ska420"
