ska-tmc-mid:
  deviceServers:
    centralnode:
      DishIDs:
      - SKA418
      - SKA420
    dishleafnode:
      instances:
      - "418"
      - "420"
    subarraynode:
      DishIDs:
      - SKA418
      - SKA420
  global:
    namespace_dish:
      dish_names:
      - "tango://tango-databaseds.dish-lmc-ska418.svc.ska418.miditf.internal.skao.int:10000/mid-dish/dish-manager/SKA418"
      - "tango://tango-databaseds.dish-lmc-ska420.svc.ska420.miditf.internal.skao.int:10000/mid-dish/dish-manager/SKA420"
  