ska-tmc-mid:
  deviceServers:
    centralnode:
      DishIDs:
      - "SKA102"
    dishleafnode:
      instances:
      - "102"
    subarraynode:
      DishIDs:
      - "SKA102"
  global:
    namespace_dish:
      dish_names:
      - "tango://tango-databaseds.dish-lmc-ska102.svc.ska418.miditf.internal.skao.int:10000/mid-dish/dish-manager/SKA102"
