team_name: atlas
team_groups:
  - atlas
  - sudo
team_users:
  - name: a.debeer
    ssh_key_path: ../../../../users/atlas/adb/.ssh/id_rsa.pub
  - name: benjamin.lunsky
    ssh_key_path: ../../../../users/atlas/bl/.ssh/id_rsa.pub
  - name: d.gammon
    ssh_key_path: ../../../../users/atlas/dg/.ssh/id_rsa.pub
  - name: g.leroux
    ssh_key_path: ../../../../users/atlas/glr/id_rsa.pub
  - name: j.coetzer
    ssh_key_path: ../../../../users/atlas/jc/.ssh/id_rsa.pub
  - name: monde.manzini
    ssh_key_path: ../../../../users/atlas/mm/.ssh/id_rsa.pub
  - name: n.nzotho
    ssh_key_path: ../../../../users/atlas/nn/.ssh/id_ed25519.pub
  - name: p.jordaan
    ssh_key_path: ../../../../users/atlas/pj/.ssh/id_rsa.pub
  - name: t.tsotetsi
    ssh_key_path: ../../../../users/atlas/tt/.ssh/id_ed25519.pub
  - name: vhulahani.manukha
    ssh_key_path: ../../../../users/atlas/vm/.ssh/id_rsa.pub
