team_name: atlas

team_groups:
  - name: atlas
    primary: true
    all: true
    admin: false
    create: true
  - name: sudo
    primary: false
    all: true
    admin: false
    create: false
  - name: atlas-admin
    primary: false
    admin: true
    all: false
    create: true
    members:
    - p.jordaan
    - a.debeer

users_dir: ../../../../users/atlas
team_users:
  - name: a.debeer
    ssh_key_path: "{{ users_dir }}/adb/.ssh/id_rsa.pub"
  - name: d.gammon
    ssh_key_path: "{{ users_dir }}/dg/.ssh/id_rsa.pub"
  - name: j.coetzer
    ssh_key_path: "{{ users_dir }}/jc/.ssh/id_rsa.pub"
  - name: monde.manzini
    ssh_key_path: "{{ users_dir }}/mm/.ssh/id_rsa.pub"
  - name: n.nzotho
    ssh_key_path: "{{ users_dir }}/nn/.ssh/id_ed25519.pub"
  - name: p.jordaan
    ssh_key_path: "{{ users_dir }}/pj/.ssh/id_rsa.pub"
  - name: t.tsotetsi
    ssh_key_path: "{{ users_dir }}/tt/.ssh/id_ed25519.pub"
  - name: vhulahani.manukha
    ssh_key_path: "{{ users_dir }}/vm/.ssh/id_rsa.pub"
remove_users:
  - g.leroux
  - b.lunsky


kube_admin_context: kubernetes-admin@kubernetes
kube_context: atlas-integration-mid-kubernetes