image: python:3.11

stages:
  - lint
  - test

.setup-ansible: &setup-ansible
  - export LC_ALL="C.UTF-8"                # ansible requires locale to be set to UTF-8.
  - export PATH=${PATH}:${HOME}/.local/bin # this is where python installs ansible.
  - python3 -m pip install --user ansible
  - python3 -m pip install --user ansible-lint

ansible-lint:
  stage: lint
  tags:
  - k8srunner
  allow_failure: true
  before_script:
    - *setup-ansible
  script:
  - cd resources/ansible-playbooks && make lint

ansible-test:
  stage: test
  tags:
  - k8srunner
  allow_failure: true
  before_script:
    - *setup-ansible
  script:
  - cd resources/ansible-playbooks && make test