---

- name: Setup raspberry_pi
  hosts:
    - raspberry_pi
  roles:
    - role: system_setup
    - role: user_setup
      vars:
        createusers: true
    - role: ssh_keys
      vars:
        addkey: true
    - role: user_config
      become: true
      vars:
        setup_kubeconfig: false

- name: Setup gaia
  hosts:
    - gaia
  roles:
    - role: system_setup
    - role: user_setup
      vars:
        add_to_groups: true
    - role: ssh_keys
      vars:
        addkey: true
    - role: user_config
      become: true
      vars:
        setup_kubeconfig: true

- name: Setup test
  hosts:
    - test
  roles:
    - role: system_setup
      vars:
        install_kubectl: true
    - role: user_setup
      vars:
        createusers: true
        add_to_groups: true
    - role: ssh_keys
      vars:
        addkey: true
    - role: user_config
      become: true
      vars:
        setup_kubeconfig: true
