ska-dish-lmc:
  ska-mid-dish-manager:
    ska-mid-dish-simulators:
      dsOpcuaSimulator:
        enabled: false

  ska-mid-dish-ds-manager:
    dishstructuremanager:
      ds_opcua_namespace: "http://www.boschrexroth.com/IndraLogic"
      dsc:
        fqdns:
          ["opc.tcp://10.165.3.42:4840/"]
