apiVersion: v2
name: ska-mid-itf-sut
description: An umbrella Helm chart for deployment of the System Under Test at the Mid ITF
type: application
version: 26.0.0-rc.3
appVersion: 26.0.0-rc.3
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  # Tango Base & Deployment Charts: TangoDB, iTango, Tango Operator Utils
  - name: ska-tango-base
    version: 0.4.15
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tango-util
    version: 0.4.15
    repository: https://artefact.skao.int/repository/helm-internal

  # SKA Mid TMC
  - name: ska-tmc-mid
    version: 0.25.0 # check latest version
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tmc-mid.enabled

  # SKA Mid CSP LMC
  - name: ska-csp-lmc-mid
    version: 1.0.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-csp-lmc-mid.enabled

  # SKA Mid CBF
  - name: ska-mid-cbf-tdc-mcs
    version: 1.1.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-mid-cbf-tdc-mcs.enabled

  - name: ska-mid-cbf-engineering-console
    version: 1.1.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-mid-cbf-engineering-console.enabled

  # SKA Mid SDP
  - name: ska-sdp
    version: 0.24.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-sdp.enabled

  # SKA Configuration Inspector API
  # Gitlab Location: https://gitlab.com/ska-telescope/ska-ser-config-inspector
  # Releases: https://gitlab.com/ska-telescope/ska-ser-config-inspector/-/releases
  - name: ska-ser-config-inspector
    version: 0.2.3 # check latest version
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-ser-config-inspector.enabled

  # TARANTA SUITE
  - name: ska-tango-taranta
    version: 2.13.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-taranta.enabled
  # MULTIDB TANGOGQL
  - name: ska-tango-tangogql-ariadne
    version: 1.0.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
    alias: tangogql

  # test helpers
  - name: ska-log-consumer
    version: 0.1.6
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-log-consumer.enabled

  # SKA Tango AlarmHandler
  - name: ska-tango-alarmhandler
    version: 0.4.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-alarmhandler.enabled

  # EDA
  - name: ska-tango-archiver
    version: 2.8.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-archiver.enabled

  # EXAMPLE DEV CHART: DON'T DELETE THIS SECTION
  # - name: ska-sdp
  #   version: 0.19.0-dev.c651132b9
  #   repository: https://gitlab.com/api/v4/projects/21141217/packages/helm/dev
