global:
  tango_host: tango-databaseds:10000
  dishes: ["100"]
  exposeDatabaseDS: true
  exposeAllDS: true
  facility: mid-itf
  minikube: false
  use_aws: true
  sub-system:
    ska-tango-base:
      enabled: false
  tangodb_fqdn: localhost
  tangodb_port: 10000
  raw_user_account: bond
  raw_user_pass: jamesbond
  dish_id: ska007

ska-tango-base:
  tangodb:
    use_pv: true
  itango:
    enabled: true

# DISH LMC
ska-dish-lmc:
  ska-tango-base:
    enabled: false
  ska-mid-dish-manager:
    enabled: true
  ska-mid-dish-ds-manager:
    enabled: true
  ska-mid-dish-simulators:
    enabled: true
    deviceServers:
      spfdevice:
        enabled: true
      spfrxdevice:
        enabled: true
    dsOpcuaSimulator:
      enabled: true
    dishleafnode:
      image:
        registry: registry.gitlab.com/ska-telescope/ska-tmc/ska-tmc-dishleafnode
        tag: 0.18.1-dev.cbb476326

# SPFRx
ska-mid-dish-spfrx-talondx-console:
  enabled: false
  console:
    version: 0.3.8-dev.c74186232 # Edit in Gitlab Environment
    registry: registry.gitlab.com/ska-telescope/ska-mid-dish-spfrx-talondx-console
  address: 10.165.3.20
  bin: /usr/local/bin
  local_dir: artifacts
  scripts_dir: scripts
  instance: spfrx-20
  logging_level: 4

# SPFC
ska-spfc-deployer:
  enabled: false

# TARANTA SUITE
ska-taranta:
  enabled: true
  ingress:
    enabled: true
    nginx: true
  tangogql:
    replicas: 1
    resources:
      requests:
        cpu: 600m # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem

# CIA
ska-ser-config-inspector:
  enabled: true

ska-tango-tangogql:
  enabled: true
  ska-tango-base:
    enabled: false
  ska-tango-examples:
    enabled: false

# EDA
ska-tango-archiver:
  enabled: true
  hostname: eda.ska-tango-archiver
  dbname: itf_eda
  dbuser: admin
  port: 5432
  telescope: SKA-mid
  telescope_environment: MID-ITF
  configuration_manager: mid-eda/cm/01
  event_subscriber: mid-eda/es/01
  archwizard_config: MyHDB=tango://tango-databaseds:10000/mid-eda/cm/01
  archviewer:
    instances:
      - name: "mid"
        timescale_host: "10.164.11.33"
        #     #keep below field empty if db names are unknown, app will display all dbs present
        #     #e.g:timescale_databases: ""
        timescale_databases: "itf_eda"
