global:
  tango_host: tango-databaseds:10000
  dishes: ["100"]
  exposeDatabaseDS: true
  exposeAllDS: true
  facility: mid-itf
  minikube: false
  sub-system:
    ska-tango-base:
      enabled: false
  tangodb_fqdn: localhost
  tangodb_port: 10000
  raw_user_account: bond
  raw_user_pass: jamesbond

# DISH LMC
dishlmc:
  ska-tango-base:
    enabled: false

  ska-mid-dish-manager:
    enabled: true
    ska-mid-dish-ds-manager:
      enabled: true

  ska-mid-dish-simulators:
    enabled: true
    deviceServers:
      spfdevice:
        enabled: true
      spfrxdevice:
        enabled: false
    dsOpcuaSimulator:
      enabled: true

# SPFRx
spfrx:
  console:
    version: 0.0.1 # Edit in Gitlab Environment
  address: 10.165.3.20
  bin: /usr/local/bin
  local_dir: artifacts
  scripts_dir: scripts
  instance: spfrx-20
  logging_level: 4

# TARANTA SUITE
ska-taranta:
  enabled: true
  ingress:
    enabled: true
    nginx: true
  tangogql:
    replicas: 1
    resources:
      requests:
        cpu: 600m # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem
