{{ if .Values.rest.enabled }}
{{ if .Values.rest.backend.filesystem.use_pv }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "ska-db-oda.name" . }}-persistent-volume-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-db-oda.labels" . | indent 4 }}
{{ if or (.Values.global.annotations) (.Values.annotations) }}
  annotations:
{{ toYaml (coalesce .Values.global.annotations .Values.annotations) | indent 4 }}
{{ end }}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.rest.backend.filesystem.pv_hostpath }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "ska-db-oda.name" . }}-persistent-volume-claim-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-db-oda.labels" . | indent 4 }}
{{ if or (.Values.global.annotations) (.Values.annotations) }}
  annotations:
{{ toYaml (coalesce .Values.global.annotations .Values.annotations) | indent 4 }}
{{ end }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{ end }}

{{ end }}
