global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  facility: mid-itf
  exposeAllDS: true
  taranta_auth_enabled: true
  taranta_dashboard_enabled: true
  sub-system:
    ska-tango-base:
      enabled: false

# SPOOKD
# TODO: We only have a single host defined here because spookd gives
# validation errors if we have multiple. We need to determine why this
# is the case so that we don't have a single POF.
spookd:
  enabled: true
  deviceMapping:
    - hosts:
        - za-itf-cloud03
      devices:
        - resourceName: skao.int/signal-generator-01
          instanceID: "0001"
          env:
            IP: 10.165.3.1
        - resourceName: skao.int/spectrum-analyser-01
          instanceID: "0001"
          env:
            IP: 10.165.3.4
            HOSTNAME: "za-itf-spectrum-analyser.ad.skatelescope.org"
