---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-mid-itf-eda-credentials
  namespace: eda-grafana-connector
spec:
  destination:
    create: true
    name: vault-mid-itf-eda-credentials
    type: Opaque
    transformation:
      excludeRaw: true
      excludes:
        - '.*'
      templates:
        eda_ro:
          text: '{{ "{{ get .Secrets \"eda_ro\" | toString }}" }}'
  mount: mid-itf
  path: production/eda
  refreshAfter: 300s
  type: kv-v2
  version: 3
---
