db: tango-databaseds.dish-lmc-ska036.svc.ska036.miditf.internal.skao.int:10000
manager: mid-eda/cm/01
archiver: mid-eda/es/01

configuration:
- class: DishManager
  attributes:
    dishmode:
      code_push_event: True
