tango_hosts:
- th1:
    host: tango-databaseds.dish-lmc-ska046.svc.ska046.mid.internal.skao.int
    port: 10000
event_subscribers:
- es1:
    trl: mid-eda/es/01
- es9:
    trl: mid-eda/es/09
configuration_managers:
- cm1:
    trl: mid-eda/cm/01
defaults:
- th: th1
- cm: cm1
- es: es1
attributes:
- trl: ska046/spf/spfc/hecompdiffpressure
  es: es1
  configuration:
    code_push_event: true
    archive_abs_change: 0.2
- trl: ska046/spf/spfc/b2bodytemp
  es: es1
  configuration:
    code_push_event: true
    archive_abs_change: 0.1
- trl: ska046/spf/spfc/hecompreturnpressure
  es: es1
  configuration:
    code_push_event: true
    archive_abs_change: 0.2
- trl: mid-dish/dish-manager/ska046/azimuthoverwrap
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/band2pointingmodelparams
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/noisediodeconfig
  es: es1
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/b2omttemp
  es: es1
  configuration:
    code_push_event: true
    archive_abs_change: 0.1
- trl: mid-dish/dish-manager/ska046/lastcommandedmode
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/buildstate
  es: es1
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/b2cryomotorstate
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/periodicnoisediodepars
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/attenuation1polhx
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/attenuation1polvy
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/attenuation2polhx
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/attenuation2polvy
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/attenuationpolhx
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/attenuationpolvy
  es: es1
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/b2coldheadstage1temp
  es: es1
  configuration:
    code_push_event: true
    archive_abs_change: 0.1
- trl: ska046/spf/spfc/b2amp2hpowerstate
  es: es1
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/b2calsourcetemp
  es: es1
  configuration:
    code_push_event: true
    archive_abs_change: 0.1
- trl: ska046/spf/spfc/hecompsupplytemp
  es: es1
  configuration:
    code_push_event: true
    archive_abs_change: 0.2
- trl: ska046/spf/spfc/hecompressorpowerstate
  es: es1
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/b2lnatemp
  es: es1
  configuration:
    code_push_event: true
    archive_abs_change: 0.1
- trl: mid-dish/dish-manager/ska046/ignorespfrx
  es: es1
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/b2amp2vpowerstate
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/band2samplerfrequency
  es: es1
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/b2cryomotorspeed
  es: es1
  configuration:
    code_push_event: true
    archive_abs_change: 1.0
- trl: ska046/spf/spfc/hecompsupplypressure
  es: es1
  configuration:
    code_push_event: true
    archive_abs_change: 0.2
- trl: mid-dish/dish-manager/ska046/noisediodemode
  es: es1
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/b2manifoldpressure
  es: es1
  configuration:
    code_push_event: true
    archive_abs_change: 0.1
- trl: ska046/spf/spfc/b2lnahpowerstate
  es: es1
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/hecompmotortemp
  es: es1
  configuration:
    code_push_event: true
    archive_abs_change: 0.1
- trl: mid-dish/dish-manager/ska046/ignorespf
  es: es1
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/b2lnavpowerstate
  es: es1
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/b2cryopressure
  es: es1
  configuration:
    code_push_event: true
    archive_abs_change: 1.0e-05
- trl: mid-dish/dish-manager/ska046/configuredband
  es: es1
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/b2calsourcepowerstate
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/pointingbuffersize
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/spfrxconnectionstate
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/dishmode
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/healthstate
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/kvalue
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/tracktableloadmode
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/spfconnectionstate
  es: es1
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/operatingmode
  es: es1
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/status
  es: es9
  configuration:
    code_push_event: true
- trl: mid-dish/dish-manager/ska046/dscerrorstatuses
  es: es9
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/b1defaultstartstate
  es: es1
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/b2defaultstartstate
  es: es1
  configuration:
    code_push_event: true
- trl: ska046/spf/spfc/b345defaultstartstate
  es: es1
  configuration:
    code_push_event: true
