apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  labels:
    app: {{ .Values.job.name }}

spec:
  template:
    spec:
      containers:
      - name: {{ .Values.job.name }}
        image: {{ .Values.job.image }}
        env:
          - name: SPFC_KEY
            value: {{ .Values.vault.key1 }}
          - name: SPFC_HOST
            value: 10.165.3.33        
        command: ["/bin/bash","-c"]
        args:
          #- echo $(curl 'http://vault-service.default.svc.cluster.local:8080');
          - bash /scripts/register_spfc.sh

        volumeMounts:
        - name: {{ .Values.volume.name }}
          mountPath: {{ .Values.mounts.setupScript.mount }}

      volumes:
        - name: {{ .Values.volume.name }}
          configMap:
            name: {{ .Values.volume.name }}


      restartPolicy: Never

      ports:
      - protocol: TCP
        port: 8200
        targetPort: 8200
  backoffLimit: 6
  suspend: false