.odt:
  tags:
    - ska-k8srunner-za-itf
  stage: on_demand_itf_sut
  variables:
    CONFIG: mid
    K8S_CHART: ska-oso-odt-services
    KUBE_APP: ska-db-odt
    INGRESS_HOST: "k8s.miditf.internal.skao.int"
    CLUSTER_DOMAIN: "miditf.internal.skao.int"
    TANGO_DATABASE_DS: tango-databaseds
    MINIKUBE: "false"
    CLUSTER_DOMAIN_POSTFIX: miditf.internal.skao.int
    KUBE_NAMESPACE: ci-ska-mid-itf-$CI_COMMIT_REF_NAME
  environment:
    name: sut/odt/$KUBE_NAMESPACE
    kubernetes:
      namespace: $KUBE_NAMESPACE
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/odt/api/v1/ui/"
  when: manual
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_PIPELINE_ID"
    paths:
      - "build/"

deploy-odt-on-demand:
  extends:
    - .odt
  variables:
    K8S_EXTRA_PARAMS: "-f charts/ska-oso-odt-services/values.yaml"
  script:
    - make k8s-install-chart
  after_script:
    - bash .make/resources/gitlab_section.sh deployment-config "Output deployment config information" make get-deployment-config-info
  environment:
    on_stop: destroy-odt-on-demand

destroy-odt-on-demand:
  extends:
    - .odt
  script:
    - make k8s-uninstall-chart || true
    - make k8s-delete-namespace KUBE_NAMESPACE=$KUBE_NAMESPACE
  environment:
    action: stop

.odt-staging:
  extends:
    - .odt
    - .staging_rules
  stage: staging
  variables:
    KUBE_NAMESPACE: staging-odt

deploy-odt-staging:
  extends:
    - .odt-staging
  variables:
    K8S_EXTRA_PARAMS: "-f charts/ska-oso-odt-services/values-staging.yaml"
  script:
    - make k8s-install-chart
  after_script:
    - bash .make/resources/gitlab_section.sh deployment-config "Output deployment config information" make get-deployment-config-info
  environment:
    on_stop: destroy-odt-staging

destroy-odt-staging:
  extends:
    - .odt-staging
  script:
    - !reference [.cleanup, script]
  environment:
    action: stop
