# ##############################################################
# # Common deployment templates (Copied from Skampi Deployments)
# ##############################################################
.deploy:
  stage: deploy
  image: $DEPLOY_IMAGE
  variables:
    SWITCH_CSP_ON: "false"
  before_script:
    - |
      if [ "$CBF_HW_IN_THE_LOOP" == "true" ]; then
        # apt-get update && apt-get install iputils-ping netcat -y
        ping -c 1 $PDU_IP || (echo "Cannot reach PDU") #FIXME: This is the type of config data that we should ideally be putting in Vault / Config database
        nc -zv $PDU_IP 22 || (echo "Cannot reach PDU SSH interface - go to  https://za-itf-pdu3.ad.skatelescope.org and reset" && exit 1)
      fi
    # - bash .make/resources/gitlab_section.sh poetry "Install Python dependencies" poetry install
  script:
    - mkdir deploy
    - bash .make/resources/gitlab_section.sh poetry "Poetry Install" poetry install
    - export PATH=.venv/bin:${PATH} # TEMPORARY COMMIT: fix in one place
    - echo $CI_JOB_NAME - $CI_JOB_STAGE > deploy/ci_details.txt # This is just to double-check if the job output to the build folder works
    - echo $CI_JOB_NAME - $CI_JOB_STAGE
    - |
      if [ "$DISH_LMC_IN_THE_LOOP" != "true" ]; then
        export TMC_VALUES_PATH=charts/ska-mid-itf-sut/values.yaml
      else
        bash .make/resources/gitlab_section.sh tmc-values "Generate tmc-values.yaml file from Dish IDs" make itf-dish-ids
      fi
    - bash .make/resources/gitlab_section.sh vars "Make config dump" make vars
    - bash .make/resources/gitlab_section.sh creds "Create K8s Credentials" make itf-cluster-credentials
    - |
      if [ "$K8S_INSTALL_FROM_CAR" != "true" ]; then
        bash .make/resources/gitlab_section.sh install "Installing $K8S_CHART Charts - not from CAR" make k8s-install-chart
      else
        bash .make/resources/gitlab_section.sh install "Installing $K8S_CHART Charts from CAR" make k8s-install-chart-car
      fi
    - bash .make/resources/gitlab_section.sh wait-ns "Wait namespace resources" make k8s-wait
    - make links
    - |
      if [ "$CBF_HW_IN_THE_LOOP" == "true" ]; then
        make itf-cbf-setup --dry && sleep 3;
        make itf-cbf-talonlru-status && sleep 3;
        bash .make/resources/gitlab_section.sh talon_off "Switch off Talon" make itf-cbf-talonlru-off && sleep 3;
        bash .make/resources/gitlab_section.sh mcs_config "Configure MCS" make itf-cbf-config-mcs && sleep 3;
        bash .make/resources/gitlab_section.sh talon_on "Talon Tango ON" make itf-cbf-tango-on && sleep 3;
      fi
    - env | grep RUNNER_AFTER_SCRIPT_TIMEOUT
    - bash .make/resources/gitlab_section.sh template "Output deployment config information" make get-deployment-config-info
  after_script:
    - make links
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_PIPELINE_ID-$CI_JOB_STAGE-$CI_JOB_NAME"
    paths:
      - "build/"
      - "deploy/"
  variables:
    SUT_CHART_DIR: ${CI_PROJECT_DIR}/charts/ska-mid-itf-sut
    RUNNER_AFTER_SCRIPT_TIMEOUT: 6m

.info:
  stage: deploy
  script:
    - bash .make/resources/gitlab_section.sh get-ns "Get namespace resources" make k8s-get
    - bash .make/resources/gitlab_section.sh get-ns-dp "Get SDP namespace resources" make k8s-get KUBE_NAMESPACE=${KUBE_NAMESPACE}-sdp
    - make k8s-info
    - make k8s-info KUBE_NAMESPACE=${KUBE_NAMESPACE}-sdp

.cleanup:
  stage: cleanup
  script: &cleanup_script
    - echo $CI_JOB_NAME - $CI_JOB_STAGE
    - bash .make/resources/gitlab_section.sh vars "Make config dump" make vars
    - bash .make/resources/gitlab_section.sh pvc-running "Check which PVCs are currently in SDP namespace" make pvc-check KUBE_NAMESPACE=$KUBE_NAMESPACE_SDP
    - make k8s-uninstall-chart || true
    - |
      if [ "$KEEP_NAMESPACE" != "true" ]; then
        make k8s-delete-namespace
        if [ "$KUBE_NAMESPACE_SDP" != "" ]; then
          make k8s-delete-namespace KUBE_NAMESPACE=$KUBE_NAMESPACE_SDP
          kubectl get pvc staging-pvc -n $KUBE_NAMESPACE_SDP > /dev/null 2>&1
          if [ $? -eq 0 ]; then
            kubectl wait --for=delete pvc/staging-pvc -n $KUBE_NAMESPACE_SDP --timeout=60s
          else
            echo "No PVC found. Continuing..."
          fi
        fi
      fi

.redeploy:
  extends:
    - .deploy
  before_script: *cleanup_script

.uninstall-chart:
  script:
    - echo $CI_JOB_NAME - $CI_JOB_STAGE
    - bash .make/resources/gitlab_section.sh vars "Make config dump" make vars
    - bash .make/resources/gitlab_section.sh env "Environment dump" env
    - make k8s-uninstall-chart || true
    - kubectl -n $KUBE_NAMESPACE delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,configmaps --all --ignore-not-found
    - make k8s-delete-namespace

# If the pipeline is being exectued as a downstream, do not lint
# or build
helm-chart-lint:
  after_script:
    - make helm-check-deps
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - exists:
        - charts/**/*

helm-chart-build:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - exists:
        - charts/**/*

docs-build:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - exists:
        - charts/**/*
